import React, { useState, useMemo } from "react";
import { TableScroll } from "../components/common/ScrollArea";
import { useAuth } from "../context/AuthContext";
import { useDatabase } from "../context/DatabaseContext";
import { OPEN_LOAN_STATUSES } from "../types/database.types";
import { formatUGX } from "../lib/loanCalculations";
import jsPDF from "jspdf";
import { autoTable } from "../lib/autoTable";
import {
  ShieldAlert,
  TrendingUp,
  TrendingDown,
  DollarSign,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Clock,
  FileText,
  BarChart2,
  Activity,
  Download,
  Filter,
  Search,
  Banknote,
  CreditCard,
  RefreshCw,
  Eye,
  FileSpreadsheet,
  Printer,
  Target,
  Scale,
  Calendar,
  Receipt,
} from "lucide-react";
import {
  ResponsiveContainer,
  AreaChart,
  Area,
  BarChart,
  Bar,
  LineChart,
  Line,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
} from "recharts";
import {
  PageHeader,
  DesktopOnly,
  MobileOnly,
  RecordCard,
  CardList,
  EmptyState,
} from "../components/mobile/Responsive";

// ─── Types ───────────────────────────────────────────────────────────────────
type AuditTab = "overview" | "loans" | "collections" | "expenses" | "bank" | "activity" | "reports";

// ─── CSV Helper ───────────────────────────────────────────────────────────────
function downloadCSV(filename: string, headers: string[], rows: string[]) {
  const csvContent = [headers.join(","), ...rows].join("\n");
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

// ─── Branded Audit PDF Header ─────────────────────────────────────────────────
function drawAuditHeader(doc: jsPDF, title: string, rn: string, generatedBy: string) {
  doc.setFillColor(15, 41, 98);
  doc.rect(0, 0, 210, 10, "F");
  doc.setFillColor(211, 47, 47);
  doc.rect(0, 10, 210, 2, "F");

  doc.setTextColor(15, 41, 98);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text("CHETU MICROFINANCE LTD", 14, 24);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text(
    "Head Office: Kampala Central  |  Tel: +256 700 123 456  |  Email: info@chetumicrofinance.co.ug",
    14,
    30,
  );
  doc.text("Plot 45 Kampala Road, P.O. Box 10294, Kampala, Uganda", 14, 35);

  doc.setFillColor(239, 246, 255);
  doc.roundedRect(122, 14, 74, 24, 3, 3, "F");
  doc.setDrawColor(30, 96, 213);
  doc.roundedRect(122, 14, 74, 24, 3, 3, "D");
  doc.setTextColor(211, 47, 47);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text(title.toUpperCase(), 159, 22, { align: "center" });
  doc.setTextColor(30, 96, 213);
  doc.setFontSize(8);
  doc.text(`Ref: ${rn}`, 159, 28, { align: "center" });
  doc.text(`Date: ${new Date().toLocaleDateString("en-UG")}`, 159, 33, { align: "center" });

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(14, 43, 196, 43);
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated By: ${generatedBy}  |  CONFIDENTIAL – Authorized Personnel Only`, 14, 49);
}

function drawAuditFooter(doc: jsPDF) {
  const total = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    const ph = doc.internal.pageSize.height;
    doc.setFillColor(248, 250, 252);
    doc.rect(0, ph - 12, 210, 12, "F");
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text(
      "Chetu Microfinance Ltd – Confidential Audit Report | Unauthorized distribution is strictly prohibited.",
      105,
      ph - 5,
      { align: "center" },
    );
    doc.text(`Page ${i} of ${total}`, 196, ph - 5, { align: "right" });
  }
}

const rn = () =>
  `AUD-${new Date().getFullYear()}-${String(Math.floor(Math.random() * 9000) + 1000)}`;

// ─── Stat Card ────────────────────────────────────────────────────────────────
interface StatCardProps {
  label: string;
  value: string;
  sub?: string;
  icon: React.ElementType;
  color: string;
  bg: string;
  trend?: "up" | "down";
}
const StatCard: React.FC<StatCardProps> = ({ label, value, sub, icon: Icon, color, bg, trend }) => (
  <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-4 flex items-start gap-3 hover:shadow-md transition-shadow">
    <div className={`p-2.5 rounded-xl ${bg} shrink-0`}>
      <Icon className={`w-5 h-5 ${color}`} />
    </div>
    <div className="min-w-0">
      <p className="text-[11px] font-semibold text-slate-500 uppercase tracking-wider leading-tight">
        {label}
      </p>
      <p className={`text-sm font-black mt-0.5 ${color} break-all`}>{value}</p>
      {sub && <p className="text-[10px] text-slate-400 mt-0.5">{sub}</p>}
      {trend === "up" && (
        <span className="inline-flex items-center gap-0.5 text-[10px] font-bold text-emerald-600 mt-0.5">
          <TrendingUp className="w-3 h-3" />
          Positive
        </span>
      )}
      {trend === "down" && (
        <span className="inline-flex items-center gap-0.5 text-[10px] font-bold text-red-500 mt-0.5">
          <TrendingDown className="w-3 h-3" />
          Needs Review
        </span>
      )}
    </div>
  </div>
);

// ─── Main Component ───────────────────────────────────────────────────────────
export const AuditDashboard: React.FC = () => {
  const { user, isAdmin, isAuditor } = useAuth();
  const {
    loans,
    loanApplications,
    repayments,
    expenses,
    bankTransactions,
    loanProducts,
    auditLogs,
    currentBankBalance,
    totalDeposits,
    totalWithdrawals,
    totalExpenses,
    totalCollectionsMonthly,
    totalCollectionsWeekly,
    totalCollectionsToday,
  } = useDatabase();

  const [activeTab, setActiveTab] = useState<AuditTab>("overview");
  const [loanFilter, setLoanFilter] = useState({
    client: "",
    status: "",
    dateFrom: "",
    dateTo: "",
    officer: "",
    product: "",
  });
  const [actSearch, setActSearch] = useState("");
  const [actRole, setActRole] = useState("");
  const generatedBy = user?.full_name || "Administrator";

  // ── Access Guard ──────────────────────────────────────────────────────────────
  if (!isAdmin && !isAuditor) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-center p-8 space-y-4">
        <div className="p-5 bg-red-100 rounded-full">
          <XCircle className="w-12 h-12 text-red-500" />
        </div>
        <h2 className="text-xl font-black text-slate-800">Access Denied</h2>
        <p className="text-sm text-slate-500 max-w-md">
          The Auditor Dashboard is restricted to Administrators and Auditors.
        </p>
      </div>
    );
  }

  // ── Aggregations ──────────────────────────────────────────────────────────────
  // Every loan still carrying a receivable, not just those literally stamped
  // `Active`. A loan moves to `Partially Paid` on its first collection, so
  // filtering on `Active` alone dropped every loan that had ever been paid
  // into — which also understated `outstandingBal` below by their whole
  // remaining balance.
  const activeLoans = loans.filter((l) => OPEN_LOAN_STATUSES.includes(l.status));
  const paidLoans = loans.filter((l) => l.status === "Fully Paid");
  const overdueLoans = loans.filter((l) => l.status === "Overdue");
  const defaultedLoans = loans.filter((l) => l.status === "Defaulted");
  const pendingApps = loanApplications.filter((a) => a.status === "Pending");
  const approvedApps = loanApplications.filter((a) => a.status === "Approved");
  const rejectedApps = loanApplications.filter((a) => a.status === "Rejected");

  const totalOutstandingInstallments = useMemo(
    () =>
      loans.reduce(
        (s, l) =>
          s +
          (l.schedule
            ?.filter((sc) => sc.status !== "Paid")
            .reduce((ss, sc) => ss + sc.remaining_balance, 0) || 0),
        0,
      ),
    [loans],
  );

  const totalDisbursed = loans
    .filter((l) => l.status !== "Pending")
    .reduce((s, l) => s + l.principal_amount, 0);
  const totalCollected = repayments.reduce((s, r) => s + r.amount_paid, 0);
  const totalInterest = loans
    .filter((l) => l.status !== "Pending")
    .reduce((s, l) => s + l.total_interest_amount, 0);
  const totalProcFees = loans
    .filter((l) => l.status !== "Pending")
    .reduce((s, l) => s + l.processing_fee_amount, 0);
  const outstandingBal = activeLoans.reduce((s, l) => s + l.outstanding_balance, 0);
  const netPortfolio = totalDisbursed - totalCollected + totalInterest;

  // Reconciliation
  const expectedBalance = totalDeposits + totalCollected - totalWithdrawals - totalExpenses;
  const variance = currentBankBalance - expectedBalance;
  const isReconciled = Math.abs(variance) < 1000;

  // Filtered loans
  const filteredLoans = useMemo(
    () =>
      loans.filter((l) => {
        if (loanFilter.status && l.status !== loanFilter.status) return false;
        if (
          loanFilter.client &&
          !l.client?.full_name.toLowerCase().includes(loanFilter.client.toLowerCase())
        )
          return false;
        if (loanFilter.product && l.product_id !== loanFilter.product) return false;
        if (loanFilter.officer) {
          const off = loanFilter.officer;
          if (l.approved_by !== off && l.disbursed_by !== off) return false;
        }
        if (loanFilter.dateFrom && l.disbursed_at && l.disbursed_at < loanFilter.dateFrom)
          return false;
        if (loanFilter.dateTo && l.disbursed_at && l.disbursed_at > loanFilter.dateTo) return false;
        return true;
      }),
    [loans, loanFilter],
  );

  // Collections by officer
  const collByOfficer = useMemo(() => {
    const map: Record<string, { name: string; total: number; count: number }> = {};
    repayments.forEach((r) => {
      const key = r.recorded_by || "unknown";
      const log = auditLogs.find((a) => a.record_id === r.receipt_number);
      const name = log?.user_name || "Loan Officer";
      if (!map[key]) map[key] = { name, total: 0, count: 0 };
      map[key].total += r.amount_paid;
      map[key].count += 1;
    });
    return Object.values(map);
  }, [repayments, auditLogs]);

  // Expense by category
  const expByCategory = useMemo(() => {
    const map: Record<string, number> = {};
    expenses.forEach((e) => {
      map[e.category] = (map[e.category] || 0) + e.amount;
    });
    return Object.entries(map).map(([name, value]) => ({ name, value }));
  }, [expenses]);

  const expByMonth = useMemo(() => {
    const map: Record<string, number> = {};
    expenses.forEach((e) => {
      const m = e.expense_date.substring(0, 7);
      map[m] = (map[m] || 0) + e.amount;
    });
    return Object.entries(map)
      .sort()
      .map(([month, total]) => ({ month, total }));
  }, [expenses]);

  // Activity filter
  const filteredLogs = useMemo(
    () =>
      auditLogs.filter((log) => {
        const q = actSearch.toLowerCase();
        if (
          actSearch &&
          ![log.action, log.user_name, log.module, log.details, log.record_id || ""].some((s) =>
            s.toLowerCase().includes(q),
          )
        )
          return false;
        if (actRole && log.user_role !== actRole) return false;
        return true;
      }),
    [auditLogs, actSearch, actRole],
  );

  // Chart data
  const loanStatusData = [
    { name: "Active", value: activeLoans.length, color: "#1e60d5" },
    { name: "Paid", value: paidLoans.length, color: "#10b981" },
    { name: "Overdue", value: overdueLoans.length, color: "#f59e0b" },
    { name: "Defaulted", value: defaultedLoans.length, color: "#ef4444" },
  ].filter((d) => d.value > 0);

  const uniqueOfficers = useMemo(() => {
    const map: Record<string, string> = {};
    auditLogs.forEach((l) => {
      if (l.user_role === "Loan Officer") map[l.user_id || l.user_name] = l.user_name;
    });
    loans.forEach((l) => {
      if (l.approved_by) map[l.approved_by] = l.approved_by;
      if (l.disbursed_by) map[l.disbursed_by] = l.disbursed_by;
    });
    return Object.entries(map).map(([id, name]) => ({ id, name }));
  }, [auditLogs, loans]);

  const monthlyData = useMemo(() => {
    const map: Record<
      string,
      { month: string; disbursed: number; collected: number; expenses: number }
    > = {};
    loans.forEach((l) => {
      if (l.disbursed_at) {
        const m = l.disbursed_at.substring(0, 7);
        if (!map[m]) map[m] = { month: m, disbursed: 0, collected: 0, expenses: 0 };
        map[m].disbursed += l.principal_amount;
      }
    });
    repayments.forEach((r) => {
      const m = r.payment_date.substring(0, 7);
      if (!map[m]) map[m] = { month: m, disbursed: 0, collected: 0, expenses: 0 };
      map[m].collected += r.amount_paid;
    });
    expenses.forEach((e) => {
      const m = e.expense_date.substring(0, 7);
      if (!map[m]) map[m] = { month: m, disbursed: 0, collected: 0, expenses: 0 };
      map[m].expenses += e.amount;
    });
    return Object.values(map).sort((a, b) => a.month.localeCompare(b.month));
  }, [loans, repayments, expenses]);

  const profitData = useMemo(
    () =>
      monthlyData.map((m) => ({
        month: m.month,
        income: m.collected + totalInterest,
        expenses: m.expenses,
        profit: m.collected + totalInterest - m.expenses,
      })),
    [monthlyData, totalInterest],
  );

  const bankTrend = useMemo(
    () =>
      bankTransactions
        .slice()
        .sort((a, b) => a.created_at.localeCompare(b.created_at))
        .map((tx) => ({ date: tx.transaction_date, balance: tx.balance_after })),
    [bankTransactions],
  );

  // ── PDF Generators ────────────────────────────────────────────────────────────
  const pdfFinancial = () => {
    const doc = new jsPDF();
    const r = rn();
    drawAuditHeader(doc, "Financial Summary Report", r, generatedBy);
    autoTable(doc, {
      startY: 54,
      head: [["Financial Metric", "Amount (UGX)"]],
      body: [
        ["Total Loans Disbursed", formatUGX(totalDisbursed)],
        ["Total Amount Collected", formatUGX(totalCollected)],
        ["Outstanding Loan Balance", formatUGX(outstandingBal)],
        ["Total Expenses", formatUGX(totalExpenses)],
        ["Total Bank Deposits", formatUGX(totalDeposits)],
        ["Total Bank Withdrawals", formatUGX(totalWithdrawals)],
        ["Current Bank Balance", formatUGX(currentBankBalance)],
        ["Net Portfolio Value", formatUGX(netPortfolio)],
        ["Total Interest Earned", formatUGX(totalInterest)],
        ["Total Processing Fees", formatUGX(totalProcFees)],
      ],
      theme: "grid",
      headStyles: { fillColor: [15, 41, 98], textColor: 255 },
      styles: { fontSize: 10 },
    });
    drawAuditFooter(doc);
    doc.save(`Financial_Summary_${r}.pdf`);
  };

  const pdfLoanAudit = () => {
    const doc = new jsPDF();
    const r = rn();
    drawAuditHeader(doc, "Loan Portfolio Audit", r, generatedBy);
    autoTable(doc, {
      startY: 54,
      head: [["Loan #", "Client", "Principal", "Outstanding", "Status", "Disbursed"]],
      body: filteredLoans.map((l) => [
        l.loan_number,
        l.client?.full_name || "N/A",
        formatUGX(l.principal_amount),
        formatUGX(l.outstanding_balance),
        l.status,
        l.disbursed_at ? l.disbursed_at.split("T")[0] : "Pending",
      ]),
      theme: "striped",
      headStyles: { fillColor: [15, 41, 98], textColor: 255 },
      styles: { fontSize: 8 },
    });
    drawAuditFooter(doc);
    doc.save(`Loan_Audit_${r}.pdf`);
  };

  const pdfExpense = () => {
    const doc = new jsPDF();
    const r = rn();
    drawAuditHeader(doc, "Expense Audit Report", r, generatedBy);
    autoTable(doc, {
      startY: 54,
      head: [["Voucher #", "Category", "Description", "Amount", "Date", "Method"]],
      body: expenses.map((e) => [
        e.expense_number,
        e.category,
        e.description.substring(0, 35),
        formatUGX(e.amount),
        e.expense_date,
        e.payment_method,
      ]),
      theme: "striped",
      headStyles: { fillColor: [211, 47, 47], textColor: 255 },
      styles: { fontSize: 8 },
    });
    drawAuditFooter(doc);
    doc.save(`Expense_Audit_${r}.pdf`);
  };

  const pdfBank = () => {
    const doc = new jsPDF();
    const r = rn();
    drawAuditHeader(doc, "Bank Transactions Audit", r, generatedBy);
    autoTable(doc, {
      startY: 54,
      head: [["Tx #", "Type", "Category", "Amount", "Balance After", "Date"]],
      body: bankTransactions.map((tx) => [
        tx.transaction_number,
        tx.transaction_type,
        tx.category,
        formatUGX(tx.amount),
        formatUGX(tx.balance_after),
        tx.transaction_date,
      ]),
      theme: "striped",
      headStyles: { fillColor: [30, 96, 213], textColor: 255 },
      styles: { fontSize: 8 },
    });
    drawAuditFooter(doc);
    doc.save(`Bank_Audit_${r}.pdf`);
  };

  const pdfActivity = () => {
    const doc = new jsPDF("landscape");
    const r = rn();
    drawAuditHeader(doc, "User Activity Audit Trail", r, generatedBy);
    autoTable(doc, {
      startY: 54,
      head: [["Timestamp", "User", "Role", "Action", "Module", "Record ID", "IP Address"]],
      body: filteredLogs.map((log) => [
        new Date(log.created_at).toLocaleString("en-UG"),
        log.user_name,
        log.user_role,
        log.action,
        log.module,
        log.record_id || "—",
        log.ip_address,
      ]),
      theme: "striped",
      headStyles: { fillColor: [15, 41, 98], textColor: 255 },
      styles: { fontSize: 7.5 },
    });
    drawAuditFooter(doc);
    doc.save(`Activity_Audit_${r}.pdf`);
  };

  const pdfCollections = () => {
    const doc = new jsPDF();
    const r = rn();
    drawAuditHeader(doc, "Collections Audit Report", r, generatedBy);
    autoTable(doc, {
      startY: 54,
      head: [["Period", "Amount"]],
      body: [
        ["Daily", formatUGX(totalCollectionsToday)],
        ["Weekly", formatUGX(totalCollectionsWeekly)],
        ["Monthly", formatUGX(totalCollectionsMonthly)],
        ["All-Time", formatUGX(totalCollected)],
      ],
      theme: "grid",
      headStyles: { fillColor: [16, 185, 129], textColor: 255 },
      styles: { fontSize: 10 },
    });
    const ny = (doc as any).lastAutoTable.finalY + 8;
    autoTable(doc, {
      startY: ny,
      head: [["Receipt #", "Client", "Amount", "Method", "Date"]],
      body: repayments.map((r2) => [
        r2.receipt_number,
        r2.client?.full_name || "N/A",
        formatUGX(r2.amount_paid),
        r2.payment_method,
        r2.payment_date,
      ]),
      theme: "striped",
      headStyles: { fillColor: [15, 41, 98], textColor: 255 },
      styles: { fontSize: 8 },
    });
    drawAuditFooter(doc);
    doc.save(`Collections_Audit_${r}.pdf`);
  };

  const pdfReconciliation = () => {
    const doc = new jsPDF();
    const r = rn();
    drawAuditHeader(doc, "Financial Reconciliation", r, generatedBy);
    autoTable(doc, {
      startY: 54,
      head: [["Ledger Item", "Amount (UGX)", "Status"]],
      body: [
        ["Total Bank Deposits", formatUGX(totalDeposits), "Recorded"],
        ["+ Loan Collections (Cash)", formatUGX(totalCollected), "Recorded"],
        ["- Total Withdrawals", formatUGX(totalWithdrawals), "Recorded"],
        ["- Total Expenses", formatUGX(totalExpenses), "Recorded"],
        ["Expected Bank Balance", formatUGX(expectedBalance), "Calculated"],
        ["Actual Bank Balance", formatUGX(currentBankBalance), "From Ledger"],
        ["Variance", formatUGX(variance), isReconciled ? "RECONCILED ✔" : "DISCREPANCY ⚠"],
      ],
      theme: "grid",
      headStyles: { fillColor: [15, 41, 98], textColor: 255 },
      styles: { fontSize: 10 },
    });
    drawAuditFooter(doc);
    doc.save(`Reconciliation_${r}.pdf`);
  };

  const pdfRepayment = () => {
    const doc = new jsPDF();
    const r = rn();
    drawAuditHeader(doc, "Repayment Audit Report", r, generatedBy);
    autoTable(doc, {
      startY: 54,
      head: [["Receipt #", "Client", "Loan #", "Amount", "Method", "Date", "Notes"]],
      body: repayments.map((rp) => [
        rp.receipt_number,
        rp.client?.full_name || "N/A",
        rp.loan?.loan_number || "N/A",
        formatUGX(rp.amount_paid),
        rp.payment_method,
        rp.payment_date,
        (rp.notes || "").substring(0, 40),
      ]),
      theme: "striped",
      headStyles: { fillColor: [16, 185, 129], textColor: 255 },
      styles: { fontSize: 8 },
    });
    drawAuditFooter(doc);
    doc.save(`Repayment_Audit_${r}.pdf`);
  };

  const pdfCashFlow = () => {
    const doc = new jsPDF();
    const r = rn();
    drawAuditHeader(doc, "Cash Flow Report", r, generatedBy);
    autoTable(doc, {
      startY: 54,
      head: [["Period", "Disbursements", "Collections", "Expenses", "Net Cash Flow"]],
      body: monthlyData.map((m) => [
        m.month,
        formatUGX(m.disbursed),
        formatUGX(m.collected),
        formatUGX(m.expenses),
        formatUGX(m.collected - m.expenses),
      ]),
      theme: "grid",
      headStyles: { fillColor: [15, 41, 98], textColor: 255 },
      styles: { fontSize: 9 },
    });
    drawAuditFooter(doc);
    doc.save(`Cash_Flow_${r}.pdf`);
  };

  const pdfMonthlyStatement = () => {
    const doc = new jsPDF();
    const r = rn();
    drawAuditHeader(doc, "Monthly Financial Statement", r, generatedBy);
    autoTable(doc, {
      startY: 54,
      head: [["Metric", "Amount (UGX)"]],
      body: [
        ["Total Loans Disbursed", formatUGX(totalDisbursed)],
        ["Total Amount Collected", formatUGX(totalCollected)],
        ["Outstanding Loan Balance", formatUGX(outstandingBal)],
        ["Total Expenses", formatUGX(totalExpenses)],
        ["Total Bank Deposits", formatUGX(totalDeposits)],
        ["Total Bank Withdrawals", formatUGX(totalWithdrawals)],
        ["Current Bank Balance", formatUGX(currentBankBalance)],
        ["Net Portfolio Value", formatUGX(netPortfolio)],
        ["Total Interest Earned", formatUGX(totalInterest)],
        ["Total Processing Fees", formatUGX(totalProcFees)],
        ["Total Profit (Collections - Expenses)", formatUGX(totalCollected - totalExpenses)],
      ],
      theme: "grid",
      headStyles: { fillColor: [15, 41, 98], textColor: 255 },
      styles: { fontSize: 10 },
    });
    drawAuditFooter(doc);
    doc.save(`Monthly_Statement_${r}.pdf`);
  };

  // ── CSV Generators ────────────────────────────────────────────────────────────
  const csvLoans = () =>
    downloadCSV(
      "loan_audit.csv",
      ["Loan #", "Client", "Principal", "Outstanding", "Status", "Disbursed Date"],
      filteredLoans.map(
        (l) =>
          `${l.loan_number},"${l.client?.full_name || "N/A"}",${l.principal_amount},${l.outstanding_balance},${l.status},${l.disbursed_at?.split("T")[0] || "Pending"}`,
      ),
    );
  const csvActivity = () =>
    downloadCSV(
      "activity_audit.csv",
      ["Timestamp", "User", "Role", "Action", "Module", "Record ID", "IP", "Device"],
      filteredLogs.map(
        (log) =>
          `"${new Date(log.created_at).toLocaleString()}","${log.user_name}","${log.user_role}","${log.action}","${log.module}","${log.record_id || ""}","${log.ip_address}","${(log.device_info || "").substring(0, 60)}"`,
      ),
    );
  const csvExpenses = () =>
    downloadCSV(
      "expense_audit.csv",
      ["Voucher #", "Category", "Description", "Amount", "Date", "Method"],
      expenses.map(
        (e) =>
          `${e.expense_number},"${e.category}","${e.description}",${e.amount},${e.expense_date},${e.payment_method}`,
      ),
    );

  const csvBank = () =>
    downloadCSV(
      "bank_transactions.csv",
      ["Tx #", "Type", "Category", "Description", "Amount", "Balance After", "Date", "Reference"],
      bankTransactions.map(
        (tx) =>
          `${tx.transaction_number},"${tx.transaction_type}","${tx.category}","${tx.description}",${tx.amount},${tx.balance_after},${tx.transaction_date},"${tx.reference_number}"`,
      ),
    );

  // ── Tabs ──────────────────────────────────────────────────────────────────────
  const tabs: { id: AuditTab; label: string; icon: React.ElementType }[] = [
    { id: "overview", label: "Overview", icon: BarChart2 },
    { id: "loans", label: "Loans", icon: FileText },
    { id: "collections", label: "Collections", icon: DollarSign },
    { id: "expenses", label: "Expenses", icon: CreditCard },
    { id: "bank", label: "Bank Ledger", icon: Banknote },
    { id: "activity", label: "Activity Trail", icon: Activity },
    { id: "reports", label: "Reports", icon: Printer },
  ];

  const BLUE = "#1e60d5";
  const GREEN = "#10b981";
  const RED = "#ef4444";
  const AMB = "#f59e0b";

  return (
    <div className="space-y-5 pb-12">
      {/* ── Page Header ── */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="min-w-0">
          <h1 className="text-xl font-black text-slate-900 flex items-center gap-2.5">
            <span className="p-2 bg-chetu-navy rounded-xl shrink-0">
              <ShieldAlert className="w-5 h-5 text-white" />
            </span>
            <span className="truncate">Auditor Dashboard</span>
          </h1>
          <p className="text-xs text-slate-500 mt-1 sm:ml-11">
            Financial integrity monitoring &amp; operational audit trail — Administrator access only
          </p>
        </div>
        <div className="flex items-center gap-2 text-xs font-bold text-slate-400 bg-slate-100 px-3 py-2 rounded-xl shrink-0">
          <RefreshCw className="w-3.5 h-3.5" />
          Live Data ·{" "}
          {new Date().toLocaleDateString("en-UG", {
            day: "numeric",
            month: "short",
            year: "numeric",
          })}
        </div>
      </div>

      {/* ── Tab Bar ── */}
      <div className="flex gap-1 bg-slate-100 p-1 rounded-2xl overflow-x-auto no-scrollbar">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold transition-all whitespace-nowrap ${activeTab === tab.id ? "bg-white text-chetu-blue shadow-sm" : "text-slate-500 hover:text-slate-800"}`}
          >
            <tab.icon className="w-3.5 h-3.5" />
            {tab.label}
          </button>
        ))}
      </div>

      {/* ════════════════════════════════════════
          OVERVIEW TAB
      ════════════════════════════════════════ */}
      {activeTab === "overview" && (
        <div className="space-y-6">
          {/* Financial Summary */}
          <section>
            <h2 className="text-sm font-black text-slate-800 mb-3 flex items-center gap-2">
              <DollarSign className="w-4 h-4 text-chetu-blue" />
              Financial Summary
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3">
              <StatCard
                label="Total Disbursed"
                value={formatUGX(totalDisbursed)}
                icon={TrendingUp}
                color="text-chetu-blue"
                bg="bg-blue-50"
                trend="up"
              />
              <StatCard
                label="Total Collected"
                value={formatUGX(totalCollected)}
                icon={CheckCircle2}
                color="text-emerald-600"
                bg="bg-emerald-50"
                trend="up"
              />
              <StatCard
                label="Outstanding Balance"
                value={formatUGX(outstandingBal)}
                icon={Clock}
                color="text-amber-600"
                bg="bg-amber-50"
              />
              <StatCard
                label="Total Expenses"
                value={formatUGX(totalExpenses)}
                icon={TrendingDown}
                color="text-red-600"
                bg="bg-red-50"
                trend="down"
              />
              <StatCard
                label="Bank Deposits"
                value={formatUGX(totalDeposits)}
                icon={Banknote}
                color="text-indigo-600"
                bg="bg-indigo-50"
                trend="up"
              />
              <StatCard
                label="Bank Withdrawals"
                value={formatUGX(totalWithdrawals)}
                icon={CreditCard}
                color="text-orange-600"
                bg="bg-orange-50"
              />
              <StatCard
                label="Bank Balance"
                value={formatUGX(currentBankBalance)}
                icon={Scale}
                color="text-chetu-blue"
                bg="bg-blue-50"
                trend="up"
              />
              <StatCard
                label="Net Portfolio Value"
                value={formatUGX(netPortfolio)}
                icon={Target}
                color="text-purple-600"
                bg="bg-purple-50"
              />
              <StatCard
                label="Interest Earned"
                value={formatUGX(totalInterest)}
                icon={TrendingUp}
                color="text-teal-600"
                bg="bg-teal-50"
                trend="up"
              />
              <StatCard
                label="Processing Fees"
                value={formatUGX(totalProcFees)}
                icon={FileText}
                color="text-cyan-600"
                bg="bg-cyan-50"
              />
            </div>
          </section>

          {/* Reconciliation */}
          <section>
            <h2 className="text-sm font-black text-slate-800 mb-3 flex items-center gap-2">
              <Scale className="w-4 h-4 text-chetu-blue" />
              Financial Reconciliation
            </h2>
            <div
              className={`rounded-2xl border-2 p-4 ${isReconciled ? "border-emerald-200 bg-emerald-50" : "border-red-300 bg-red-50"}`}
            >
              <div className="flex items-center gap-3 mb-4">
                {isReconciled ? (
                  <CheckCircle2 className="w-7 h-7 text-emerald-500 shrink-0" />
                ) : (
                  <AlertTriangle className="w-7 h-7 text-red-500 shrink-0" />
                )}
                <div>
                  <p
                    className={`text-sm font-black ${isReconciled ? "text-emerald-800" : "text-red-800"}`}
                  >
                    {isReconciled
                      ? "Books Reconciled – No Discrepancies Found"
                      : `⚠ Discrepancy Detected: ${formatUGX(Math.abs(variance))}`}
                  </p>
                  <p className="text-[11px] text-slate-500">
                    Formula: Deposits + Collections – Withdrawals – Expenses = Bank Balance
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2 text-center">
                {[
                  { label: "Bank Deposits", val: totalDeposits },
                  { label: "+ Collections", val: totalCollected },
                  { label: "– Withdrawals", val: totalWithdrawals },
                  { label: "– Expenses", val: totalExpenses },
                  { label: "Expected Balance", val: expectedBalance },
                  { label: "Actual Balance", val: currentBankBalance },
                ].map((item) => (
                  <div key={item.label} className="bg-white rounded-xl p-2 border border-slate-200">
                    <p className="text-[10px] text-slate-500 font-semibold leading-tight">
                      {item.label}
                    </p>
                    <p className="text-xs font-black text-slate-800 mt-0.5">
                      {formatUGX(item.val)}
                    </p>
                  </div>
                ))}
              </div>
              <div className="mt-3 flex justify-end">
                <button
                  onClick={pdfReconciliation}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-chetu-blue text-white rounded-xl text-[11px] font-bold hover:bg-chetu-darkblue transition-colors"
                >
                  <Download className="w-3 h-3" />
                  Export Reconciliation PDF
                </button>
              </div>
            </div>
          </section>

          {/* Charts */}
          <section>
            <h2 className="text-sm font-black text-slate-800 mb-3 flex items-center gap-2">
              <BarChart2 className="w-4 h-4 text-chetu-blue" />
              Portfolio Analytics
            </h2>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
              {/* Loan Status Pie */}
              <div className="bg-white rounded-2xl border border-slate-200 p-4">
                <p className="text-xs font-black text-slate-700 mb-3">Loan Status Distribution</p>
                <ResponsiveContainer width="100%" height={220}>
                  <PieChart>
                    <Pie
                      data={loanStatusData}
                      cx="50%"
                      cy="50%"
                      outerRadius={78}
                      dataKey="value"
                      nameKey="name"
                      label={({ name, value }) => `${name}: ${value}`}
                      labelLine={true}
                    >
                      {loanStatusData.map((entry, i) => (
                        <Cell key={i} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip formatter={(v: number) => [`${v} loans`, ""]} />
                    <Legend />
                  </PieChart>
                </ResponsiveContainer>
              </div>

              {/* Monthly Bar */}
              <div className="bg-white rounded-2xl border border-slate-200 p-4">
                <p className="text-xs font-black text-slate-700 mb-3">
                  Monthly Disbursements vs Collections vs Expenses
                </p>
                <ResponsiveContainer width="100%" height={220}>
                  <BarChart data={monthlyData} margin={{ top: 0, right: 8, left: 0, bottom: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                    <XAxis dataKey="month" tick={{ fontSize: 9 }} />
                    <YAxis
                      tick={{ fontSize: 9 }}
                      tickFormatter={(v) => `${(v / 1e6).toFixed(0)}M`}
                    />
                    <Tooltip formatter={(v: number) => [formatUGX(v), ""]} />
                    <Legend wrapperStyle={{ fontSize: 11 }} />
                    <Bar dataKey="disbursed" name="Disbursed" fill={BLUE} radius={[4, 4, 0, 0]} />
                    <Bar dataKey="collected" name="Collected" fill={GREEN} radius={[4, 4, 0, 0]} />
                    <Bar dataKey="expenses" name="Expenses" fill={RED} radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>

              {/* Bank Balance Area */}
              <div className="bg-white rounded-2xl border border-slate-200 p-4">
                <p className="text-xs font-black text-slate-700 mb-3">Bank Balance Trend</p>
                <ResponsiveContainer width="100%" height={220}>
                  <AreaChart data={bankTrend}>
                    <defs>
                      <linearGradient id="bg1" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor={BLUE} stopOpacity={0.15} />
                        <stop offset="95%" stopColor={BLUE} stopOpacity={0} />
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                    <XAxis dataKey="date" tick={{ fontSize: 9 }} />
                    <YAxis
                      tick={{ fontSize: 9 }}
                      tickFormatter={(v) => `${(v / 1e6).toFixed(0)}M`}
                    />
                    <Tooltip formatter={(v: number) => [formatUGX(v), "Balance"]} />
                    <Area
                      type="monotone"
                      dataKey="balance"
                      stroke={BLUE}
                      fill="url(#bg1)"
                      strokeWidth={2.5}
                      dot={{ fill: BLUE, r: 3 }}
                    />
                  </AreaChart>
                </ResponsiveContainer>
              </div>

              {/* Collections by Officer */}
              <div className="bg-white rounded-2xl border border-slate-200 p-4">
                <p className="text-xs font-black text-slate-700 mb-3">
                  Collections by Loan Officer
                </p>
                <ResponsiveContainer width="100%" height={220}>
                  <BarChart data={collByOfficer} layout="vertical">
                    <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                    <XAxis
                      type="number"
                      tick={{ fontSize: 9 }}
                      tickFormatter={(v) => `${(v / 1e6).toFixed(1)}M`}
                    />
                    <YAxis dataKey="name" type="category" tick={{ fontSize: 9 }} width={100} />
                    <Tooltip formatter={(v: number) => [formatUGX(v), "Collected"]} />
                    <Bar
                      dataKey="total"
                      name="Total Collected"
                      fill={GREEN}
                      radius={[0, 4, 4, 0]}
                    />
                  </BarChart>
                </ResponsiveContainer>
              </div>

              {/* Monthly Profit Trend */}
              <div className="bg-white rounded-2xl border border-slate-200 p-4">
                <p className="text-xs font-black text-slate-700 mb-3">Monthly Profit Trend</p>
                <ResponsiveContainer width="100%" height={220}>
                  <LineChart data={profitData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                    <XAxis dataKey="month" tick={{ fontSize: 9 }} />
                    <YAxis
                      tick={{ fontSize: 9 }}
                      tickFormatter={(v) => `${(v / 1e6).toFixed(1)}M`}
                    />
                    <Tooltip formatter={(v: number) => [formatUGX(v), ""]} />
                    <Legend wrapperStyle={{ fontSize: 11 }} />
                    <Line
                      type="monotone"
                      dataKey="income"
                      name="Income"
                      stroke={GREEN}
                      strokeWidth={2.5}
                      dot={{ fill: GREEN, r: 3 }}
                    />
                    <Line
                      type="monotone"
                      dataKey="expenses"
                      name="Expenses"
                      stroke={RED}
                      strokeWidth={2.5}
                      dot={{ fill: RED, r: 3 }}
                    />
                    <Line
                      type="monotone"
                      dataKey="profit"
                      name="Net Profit"
                      stroke={BLUE}
                      strokeWidth={2.5}
                      dot={{ fill: BLUE, r: 3 }}
                    />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>
          </section>
        </div>
      )}

      {/* ════════════════════════════════════════
          LOANS TAB
      ════════════════════════════════════════ */}
      {activeTab === "loans" && (
        <div className="space-y-4">
          {/* Status Badges */}
          <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2">
            {[
              {
                label: "Active",
                val: activeLoans.length,
                cls: "bg-blue-100 text-blue-800 border-blue-200",
              },
              {
                label: "Fully Paid",
                val: paidLoans.length,
                cls: "bg-emerald-100 text-emerald-800 border-emerald-200",
              },
              {
                label: "Overdue",
                val: overdueLoans.length,
                cls: "bg-amber-100 text-amber-800 border-amber-200",
              },
              {
                label: "Defaulted",
                val: defaultedLoans.length,
                cls: "bg-red-100 text-red-800 border-red-200",
              },
              {
                label: "Pending Apps",
                val: pendingApps.length,
                cls: "bg-slate-100 text-slate-800 border-slate-200",
              },
              {
                label: "Approved",
                val: approvedApps.length,
                cls: "bg-indigo-100 text-indigo-800 border-indigo-200",
              },
              {
                label: "Rejected",
                val: rejectedApps.length,
                cls: "bg-rose-100 text-rose-800 border-rose-200",
              },
            ].map((item) => (
              <div
                key={item.label}
                className={`rounded-xl border-2 px-3 py-2.5 text-center ${item.cls}`}
              >
                <p className="text-2xl font-black">{item.val}</p>
                <p className="text-[10px] font-bold leading-tight">{item.label}</p>
              </div>
            ))}
          </div>

          {/* Filters */}
          <div className="bg-white rounded-2xl border border-slate-200 p-4">
            <p className="text-xs font-black text-slate-700 flex items-center gap-1.5 mb-3">
              <Filter className="w-3.5 h-3.5 text-chetu-blue" />
              Filter Loans
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
              <input
                placeholder="Search client name…"
                value={loanFilter.client}
                onChange={(e) => setLoanFilter((p) => ({ ...p, client: e.target.value }))}
                className="border border-slate-300 rounded-xl px-3 py-2 text-xs focus:ring-2 focus:ring-chetu-blue focus:outline-none"
              />
              <select
                value={loanFilter.product}
                onChange={(e) => setLoanFilter((p) => ({ ...p, product: e.target.value }))}
                className="border border-slate-300 rounded-xl px-3 py-2 text-xs focus:ring-2 focus:ring-chetu-blue focus:outline-none"
              >
                <option value="">All Products</option>
                {loanProducts.map((p) => (
                  <option key={p.id} value={p.id}>
                    {p.product_name}
                  </option>
                ))}
              </select>
              <select
                value={loanFilter.officer}
                onChange={(e) => setLoanFilter((p) => ({ ...p, officer: e.target.value }))}
                className="border border-slate-300 rounded-xl px-3 py-2 text-xs focus:ring-2 focus:ring-chetu-blue focus:outline-none"
              >
                <option value="">All Loan Officers</option>
                {uniqueOfficers.map((o) => (
                  <option key={o.id} value={o.id}>
                    {o.name}
                  </option>
                ))}
              </select>
              <select
                value={loanFilter.status}
                onChange={(e) => setLoanFilter((p) => ({ ...p, status: e.target.value }))}
                className="border border-slate-300 rounded-xl px-3 py-2 text-xs focus:ring-2 focus:ring-chetu-blue focus:outline-none"
              >
                <option value="">All Statuses</option>
                {[
                  "Active",
                  "Partially Paid",
                  "Fully Paid",
                  "Overdue",
                  "Defaulted",
                  "Settled",
                  "Written Off",
                ].map((s) => (
                  <option key={s}>{s}</option>
                ))}
              </select>
              <input
                type="date"
                value={loanFilter.dateFrom}
                onChange={(e) => setLoanFilter((p) => ({ ...p, dateFrom: e.target.value }))}
                className="border border-slate-300 rounded-xl px-3 py-2 text-xs focus:ring-2 focus:ring-chetu-blue focus:outline-none"
              />
              <input
                type="date"
                value={loanFilter.dateTo}
                onChange={(e) => setLoanFilter((p) => ({ ...p, dateTo: e.target.value }))}
                className="border border-slate-300 rounded-xl px-3 py-2 text-xs focus:ring-2 focus:ring-chetu-blue focus:outline-none"
              />
            </div>
          </div>

          {/* Export row */}
          <div className="flex gap-2 flex-wrap items-center">
            <button
              onClick={pdfLoanAudit}
              className="flex items-center gap-1.5 px-3 py-2 bg-chetu-blue text-white rounded-xl text-xs font-bold hover:bg-chetu-darkblue transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              PDF
            </button>
            <button
              onClick={csvLoans}
              className="flex items-center gap-1.5 px-3 py-2 bg-emerald-600 text-white rounded-xl text-xs font-bold hover:bg-emerald-700 transition-colors"
            >
              <FileSpreadsheet className="w-3.5 h-3.5" />
              CSV
            </button>
            <span className="text-xs text-slate-400">{filteredLoans.length} loans</span>
          </div>

          {/* Table */}
          <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden">
            <DesktopOnly>
              <TableScroll>
                <table className="w-full min-w-[820px] text-xs">
                  <thead>
                    <tr className="bg-chetu-navy text-white">
                      {[
                        "Loan #",
                        "Client",
                        "Product",
                        "Principal",
                        "Interest",
                        "Outstanding",
                        "Status",
                        "Disbursed",
                      ].map((h) => (
                        <th
                          key={h}
                          className="px-3 py-2.5 text-left font-bold text-[11px] uppercase tracking-wider"
                        >
                          {h}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {filteredLoans.length === 0 ? (
                      <tr>
                        <td colSpan={8} className="py-10 text-center text-slate-400">
                          No loans match the selected filters.
                        </td>
                      </tr>
                    ) : (
                      filteredLoans.map((loan) => (
                        <tr key={loan.id} className="hover:bg-slate-50 transition-colors">
                          <td className="px-3 py-2.5 font-mono font-bold text-chetu-blue">
                            {loan.loan_number}
                          </td>
                          <td className="px-3 py-2.5 font-semibold text-slate-800">
                            {loan.client?.full_name || "—"}
                          </td>
                          <td className="px-3 py-2.5 text-slate-500">
                            {loan.product?.product_name || "Business Loan"}
                          </td>
                          <td className="px-3 py-2.5 font-bold text-slate-800">
                            {formatUGX(loan.principal_amount)}
                          </td>
                          <td className="px-3 py-2.5 text-teal-700">
                            {formatUGX(loan.total_interest_amount)}
                          </td>
                          <td className="px-3 py-2.5 font-bold text-amber-700">
                            {formatUGX(loan.outstanding_balance)}
                          </td>
                          <td className="px-3 py-2.5">
                            <span
                              className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${loan.status === "Active" ? "bg-blue-100 text-blue-800" : loan.status === "Fully Paid" ? "bg-emerald-100 text-emerald-800" : loan.status === "Overdue" ? "bg-amber-100 text-amber-800" : "bg-red-100 text-red-800"}`}
                            >
                              {loan.status}
                            </span>
                          </td>
                          <td className="px-3 py-2.5 text-slate-500">
                            {loan.disbursed_at ? loan.disbursed_at.split("T")[0] : "—"}
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </TableScroll>
            </DesktopOnly>

            <MobileOnly className="p-3">
              {filteredLoans.length === 0 ? (
                <EmptyState icon={FileText} title="No loans match the selected filters." />
              ) : (
                <CardList>
                  {filteredLoans.map((loan) => (
                    <RecordCard
                      key={loan.id}
                      title={loan.loan_number}
                      subtitle={loan.client?.full_name || "—"}
                      badge={
                        <span
                          className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${loan.status === "Active" ? "bg-blue-100 text-blue-800" : loan.status === "Fully Paid" ? "bg-emerald-100 text-emerald-800" : loan.status === "Overdue" ? "bg-amber-100 text-amber-800" : "bg-red-100 text-red-800"}`}
                        >
                          {loan.status}
                        </span>
                      }
                      fields={[
                        { label: "Product", value: loan.product?.product_name || "Business Loan" },
                        { label: "Principal", value: formatUGX(loan.principal_amount) },
                        { label: "Interest", value: formatUGX(loan.total_interest_amount) },
                        { label: "Outstanding", value: formatUGX(loan.outstanding_balance) },
                        {
                          label: "Disbursed",
                          value: loan.disbursed_at ? loan.disbursed_at.split("T")[0] : "—",
                        },
                      ]}
                    />
                  ))}
                </CardList>
              )}
            </MobileOnly>
          </div>
        </div>
      )}

      {/* ════════════════════════════════════════
          COLLECTIONS TAB
      ════════════════════════════════════════ */}
      {activeTab === "collections" && (
        <div className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <StatCard
              label="Daily Collections"
              value={formatUGX(totalCollectionsToday)}
              sub={new Date().toLocaleDateString("en-UG")}
              icon={Calendar}
              color="text-chetu-blue"
              bg="bg-blue-50"
            />
            <StatCard
              label="Weekly Collections"
              value={formatUGX(totalCollectionsWeekly)}
              sub="Last 7 days"
              icon={TrendingUp}
              color="text-emerald-600"
              bg="bg-emerald-50"
              trend="up"
            />
            <StatCard
              label="Monthly Collections"
              value={formatUGX(totalCollectionsMonthly)}
              sub="Current month"
              icon={BarChart2}
              color="text-purple-600"
              bg="bg-purple-50"
              trend="up"
            />
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="bg-white rounded-2xl border border-amber-200 p-4 text-center">
              <p className="text-xs font-semibold text-amber-600 mb-1">Missed Installments</p>
              <p className="text-3xl font-black text-amber-700">
                {overdueLoans.reduce(
                  (s, l) => s + (l.schedule?.filter((sc) => sc.status === "Overdue").length || 0),
                  0,
                )}
              </p>
            </div>
            <div className="bg-white rounded-2xl border border-red-200 p-4 text-center">
              <p className="text-xs font-semibold text-red-600 mb-1">Overdue Loans</p>
              <p className="text-3xl font-black text-red-700">{overdueLoans.length}</p>
            </div>
            <div className="bg-white rounded-2xl border border-slate-200 p-4 text-center">
              <p className="text-xs font-semibold text-slate-600 mb-1">Total Repayments</p>
              <p className="text-3xl font-black text-slate-800">{repayments.length}</p>
            </div>
            <div className="bg-white rounded-2xl border border-orange-200 p-4 text-center">
              <p className="text-xs font-semibold text-orange-600 mb-1">Outstanding Installments</p>
              <p className="text-3xl font-black text-orange-700">
                {formatUGX(totalOutstandingInstallments)}
              </p>
            </div>
          </div>

          {/* By Officer */}
          <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden">
            <div className="px-4 py-3 bg-slate-50 border-b border-slate-200 flex items-center justify-between flex-wrap gap-2">
              <p className="text-xs font-black text-slate-700">Collections by Loan Officer</p>
              <button
                onClick={pdfCollections}
                className="flex items-center gap-1.5 px-3 py-1.5 bg-chetu-blue text-white rounded-xl text-[11px] font-bold hover:bg-chetu-darkblue transition-colors"
              >
                <Download className="w-3 h-3" />
                Export PDF
              </button>
            </div>
            <DesktopOnly>
              <table className="w-full text-xs">
                <thead>
                  <tr className="bg-slate-100">
                    <th className="px-4 py-2.5 text-left font-bold uppercase tracking-wider text-slate-600">
                      Officer
                    </th>
                    <th className="px-4 py-2.5 text-left font-bold uppercase tracking-wider text-slate-600">
                      # Repayments
                    </th>
                    <th className="px-4 py-2.5 text-left font-bold uppercase tracking-wider text-slate-600">
                      Total Collected
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {collByOfficer.map((o, i) => (
                    <tr key={i} className="hover:bg-slate-50">
                      <td className="px-4 py-2.5 font-semibold text-slate-800">{o.name}</td>
                      <td className="px-4 py-2.5 text-slate-600">{o.count}</td>
                      <td className="px-4 py-2.5 font-bold text-emerald-700">
                        {formatUGX(o.total)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </DesktopOnly>
            <MobileOnly className="p-3">
              {collByOfficer.length === 0 ? (
                <EmptyState icon={DollarSign} title="No collections recorded yet." />
              ) : (
                <CardList>
                  {collByOfficer.map((o, i) => (
                    <RecordCard
                      key={i}
                      title={o.name}
                      fields={[
                        { label: "# Repayments", value: o.count },
                        { label: "Total Collected", value: formatUGX(o.total) },
                      ]}
                    />
                  ))}
                </CardList>
              )}
            </MobileOnly>
          </div>

          {/* All Repayments */}
          <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden">
            <div className="px-4 py-3 bg-slate-50 border-b border-slate-200">
              <p className="text-xs font-black text-slate-700">All Repayment Records</p>
            </div>
            <DesktopOnly>
              <TableScroll>
                <table className="w-full min-w-[700px] text-xs">
                  <thead>
                    <tr className="bg-slate-100">
                      {["Receipt #", "Client", "Loan #", "Amount Paid", "Method", "Date"].map(
                        (h) => (
                          <th
                            key={h}
                            className="px-3 py-2.5 text-left font-bold uppercase tracking-wider text-slate-600"
                          >
                            {h}
                          </th>
                        ),
                      )}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {repayments.map((r) => (
                      <tr key={r.id} className="hover:bg-slate-50">
                        <td className="px-3 py-2 font-mono font-bold text-chetu-blue">
                          {r.receipt_number}
                        </td>
                        <td className="px-3 py-2 font-semibold text-slate-800">
                          {r.client?.full_name || "—"}
                        </td>
                        <td className="px-3 py-2 text-slate-600">{r.loan?.loan_number || "—"}</td>
                        <td className="px-3 py-2 font-bold text-emerald-700">
                          {formatUGX(r.amount_paid)}
                        </td>
                        <td className="px-3 py-2 text-slate-600">{r.payment_method}</td>
                        <td className="px-3 py-2 text-slate-500">{r.payment_date}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </TableScroll>
            </DesktopOnly>
            <MobileOnly className="p-3">
              {repayments.length === 0 ? (
                <EmptyState icon={Receipt} title="No repayment records found." />
              ) : (
                <CardList>
                  {repayments.map((r) => (
                    <RecordCard
                      key={r.id}
                      title={r.receipt_number}
                      subtitle={r.client?.full_name || "—"}
                      fields={[
                        { label: "Loan #", value: r.loan?.loan_number || "—" },
                        { label: "Amount Paid", value: formatUGX(r.amount_paid) },
                        { label: "Method", value: r.payment_method },
                        { label: "Date", value: r.payment_date },
                      ]}
                    />
                  ))}
                </CardList>
              )}
            </MobileOnly>
          </div>
        </div>
      )}

      {/* ════════════════════════════════════════
          EXPENSES TAB
      ════════════════════════════════════════ */}
      {activeTab === "expenses" && (
        <div className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <StatCard
              label="Total Expenses"
              value={formatUGX(totalExpenses)}
              icon={TrendingDown}
              color="text-red-600"
              bg="bg-red-50"
            />
            <StatCard
              label="Total Vouchers"
              value={expenses.length.toString()}
              icon={FileText}
              color="text-slate-700"
              bg="bg-slate-100"
            />
            <StatCard
              label="Categories"
              value={expByCategory.length.toString()}
              icon={BarChart2}
              color="text-purple-600"
              bg="bg-purple-50"
            />
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            {/* By category bars */}
            <div className="bg-white rounded-2xl border border-slate-200 p-4">
              <p className="text-xs font-black text-slate-700 mb-3">Expenses by Category</p>
              <div className="space-y-2.5">
                {expByCategory.map((cat) => (
                  <div key={cat.name} className="flex items-center justify-between gap-3">
                    <span className="text-xs font-semibold text-slate-700 w-24 truncate shrink-0">
                      {cat.name}
                    </span>
                    <div className="flex-1 h-2 bg-slate-100 rounded-full overflow-hidden">
                      <div
                        className="h-full bg-chetu-blue rounded-full"
                        style={{ width: `${(cat.value / totalExpenses) * 100}%` }}
                      />
                    </div>
                    <span className="text-xs font-bold text-red-700 w-28 text-right shrink-0">
                      {formatUGX(cat.value)}
                    </span>
                  </div>
                ))}
              </div>
            </div>
            {/* Monthly chart */}
            <div className="bg-white rounded-2xl border border-slate-200 p-4">
              <p className="text-xs font-black text-slate-700 mb-3">Monthly Expense Totals</p>
              {expByMonth.length > 0 ? (
                <ResponsiveContainer width="100%" height={200}>
                  <BarChart data={expByMonth}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                    <XAxis dataKey="month" tick={{ fontSize: 9 }} />
                    <YAxis
                      tick={{ fontSize: 9 }}
                      tickFormatter={(v) => `${(v / 1e6).toFixed(1)}M`}
                    />
                    <Tooltip formatter={(v: number) => [formatUGX(v), "Expenses"]} />
                    <Bar dataKey="total" fill={RED} radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              ) : (
                <p className="text-xs text-slate-400 text-center py-8">No expense data yet.</p>
              )}
            </div>
          </div>

          {/* Expense Table */}
          <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden">
            <div className="px-4 py-3 bg-slate-50 border-b border-slate-200 flex items-center justify-between flex-wrap gap-2">
              <p className="text-xs font-black text-slate-700">
                Expense Ledger ({expenses.length} vouchers)
              </p>
              <div className="flex gap-2">
                <button
                  onClick={pdfExpense}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-red-600 text-white rounded-xl text-[11px] font-bold hover:bg-red-700 transition-colors"
                >
                  <Download className="w-3 h-3" />
                  PDF
                </button>
                <button
                  onClick={csvExpenses}
                  className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-600 text-white rounded-xl text-[11px] font-bold hover:bg-emerald-700 transition-colors"
                >
                  <FileSpreadsheet className="w-3 h-3" />
                  CSV
                </button>
              </div>
            </div>
            <TableScroll>
              <table className="w-full min-w-[750px] text-xs">
                <thead>
                  <tr className="bg-slate-100">
                    {[
                      "Voucher #",
                      "Category",
                      "Description",
                      "Amount",
                      "Date",
                      "Method",
                      "Posted By",
                      "Receipt",
                    ].map((h) => (
                      <th
                        key={h}
                        className="px-3 py-2.5 text-left font-bold uppercase tracking-wider text-slate-600"
                      >
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {expenses.map((e) => (
                    <tr key={e.id} className="hover:bg-slate-50">
                      <td className="px-3 py-2 font-mono font-bold text-red-600">
                        {e.expense_number}
                      </td>
                      <td className="px-3 py-2">
                        <span className="bg-slate-100 text-slate-700 px-2 py-0.5 rounded-full font-semibold text-[10px]">
                          {e.category}
                        </span>
                      </td>
                      <td className="px-3 py-2 text-slate-600 max-w-[200px] truncate">
                        {e.description}
                      </td>
                      <td className="px-3 py-2 font-black text-red-700">{formatUGX(e.amount)}</td>
                      <td className="px-3 py-2 text-slate-500">{e.expense_date}</td>
                      <td className="px-3 py-2 text-slate-600">{e.payment_method}</td>
                      <td className="px-3 py-2 text-slate-600">{e.recorded_by}</td>
                      <td className="px-3 py-2 text-slate-400">
                        {e.receipt_url ? (
                          <a
                            href={e.receipt_url}
                            target="_blank"
                            rel="noreferrer"
                            className="text-chetu-blue underline"
                          >
                            View
                          </a>
                        ) : (
                          "—"
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </TableScroll>
          </div>
        </div>
      )}

      {/* ════════════════════════════════════════
          BANK LEDGER TAB
      ════════════════════════════════════════ */}
      {activeTab === "bank" && (
        <div className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <StatCard
              label="Total Deposits"
              value={formatUGX(totalDeposits)}
              icon={TrendingUp}
              color="text-chetu-blue"
              bg="bg-blue-50"
              trend="up"
            />
            <StatCard
              label="Total Withdrawals"
              value={formatUGX(totalWithdrawals)}
              icon={TrendingDown}
              color="text-red-600"
              bg="bg-red-50"
            />
            <StatCard
              label="Current Bank Bal."
              value={formatUGX(currentBankBalance)}
              icon={Banknote}
              color="text-emerald-700"
              bg="bg-emerald-50"
              trend="up"
            />
          </div>
          <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden">
            <div className="px-4 py-3 bg-slate-50 border-b border-slate-200 flex items-center justify-between flex-wrap gap-2">
              <p className="text-xs font-black text-slate-700">Full Bank Transaction Ledger</p>
              <button
                onClick={pdfBank}
                className="flex items-center gap-1.5 px-3 py-1.5 bg-chetu-blue text-white rounded-xl text-[11px] font-bold hover:bg-chetu-darkblue transition-colors"
              >
                <Download className="w-3 h-3" />
                Export PDF
              </button>
              <button
                onClick={csvBank}
                className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-600 text-white rounded-xl text-[11px] font-bold hover:bg-emerald-700 transition-colors"
              >
                <FileSpreadsheet className="w-3 h-3" />
                Export CSV
              </button>
            </div>
            <TableScroll>
              <table className="w-full min-w-[860px] text-xs">
                <thead>
                  <tr className="bg-chetu-navy text-white">
                    {[
                      "Tx #",
                      "Type",
                      "Category",
                      "Description",
                      "Amount",
                      "Balance After",
                      "Date",
                      "Reference",
                    ].map((h) => (
                      <th
                        key={h}
                        className="px-3 py-2.5 text-left font-bold text-[11px] uppercase tracking-wider"
                      >
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {bankTransactions.map((tx) => (
                    <tr key={tx.id} className="hover:bg-slate-50">
                      <td className="px-3 py-2.5 font-mono font-bold text-chetu-blue">
                        {tx.transaction_number}
                      </td>
                      <td className="px-3 py-2.5">
                        <span
                          className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${tx.transaction_type === "Deposit" ? "bg-emerald-100 text-emerald-800" : "bg-red-100 text-red-800"}`}
                        >
                          {tx.transaction_type}
                        </span>
                      </td>
                      <td className="px-3 py-2.5 text-slate-600">{tx.category}</td>
                      <td className="px-3 py-2.5 text-slate-600 max-w-[180px] truncate">
                        {tx.description}
                      </td>
                      <td
                        className={`px-3 py-2.5 font-black ${tx.transaction_type === "Deposit" ? "text-emerald-700" : "text-red-700"}`}
                      >
                        {formatUGX(tx.amount)}
                      </td>
                      <td className="px-3 py-2.5 font-bold text-slate-800">
                        {formatUGX(tx.balance_after)}
                      </td>
                      <td className="px-3 py-2.5 text-slate-500">{tx.transaction_date}</td>
                      <td className="px-3 py-2.5 font-mono text-slate-400">
                        {tx.reference_number}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </TableScroll>
          </div>
        </div>
      )}

      {/* ════════════════════════════════════════
          ACTIVITY TRAIL TAB
      ════════════════════════════════════════ */}
      {activeTab === "activity" && (
        <div className="space-y-4">
          {/* Search */}
          <div className="bg-white rounded-2xl border border-slate-200 p-4">
            <p className="text-xs font-black text-slate-700 flex items-center gap-1.5 mb-3">
              <Search className="w-3.5 h-3.5 text-chetu-blue" />
              Search &amp; Filter Activity
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
                <input
                  placeholder="User, action, module, record ID…"
                  value={actSearch}
                  onChange={(e) => setActSearch(e.target.value)}
                  className="w-full pl-9 pr-3 py-2 border border-slate-300 rounded-xl text-xs focus:ring-2 focus:ring-chetu-blue focus:outline-none"
                />
              </div>
              <select
                value={actRole}
                onChange={(e) => setActRole(e.target.value)}
                className="border border-slate-300 rounded-xl px-3 py-2 text-xs focus:ring-2 focus:ring-chetu-blue focus:outline-none"
              >
                <option value="">All Roles</option>
                <option>Administrator</option>
                <option>Loan Officer</option>
              </select>
            </div>
          </div>
          <div className="flex gap-2 flex-wrap items-center">
            <button
              onClick={pdfActivity}
              className="flex items-center gap-1.5 px-3 py-2 bg-chetu-blue text-white rounded-xl text-xs font-bold hover:bg-chetu-darkblue transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              PDF
            </button>
            <button
              onClick={csvActivity}
              className="flex items-center gap-1.5 px-3 py-2 bg-emerald-600 text-white rounded-xl text-xs font-bold hover:bg-emerald-700 transition-colors"
            >
              <FileSpreadsheet className="w-3.5 h-3.5" />
              CSV
            </button>
            <span className="text-xs text-slate-400">
              {filteredLogs.length} of {auditLogs.length} entries
            </span>
          </div>
          <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden">
            <TableScroll>
              <table className="w-full min-w-[960px] text-xs">
                <thead>
                  <tr className="bg-chetu-navy text-white">
                    {[
                      "Timestamp",
                      "User",
                      "Role",
                      "Action",
                      "Module",
                      "Record ID",
                      "IP Address",
                      "Device",
                    ].map((h) => (
                      <th
                        key={h}
                        className="px-3 py-2.5 text-left font-bold text-[11px] uppercase tracking-wider"
                      >
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {filteredLogs.length === 0 ? (
                    <tr>
                      <td colSpan={8} className="py-10 text-center text-slate-400">
                        No activity logs match your search.
                      </td>
                    </tr>
                  ) : (
                    filteredLogs.map((log) => (
                      <tr key={log.id} className="hover:bg-slate-50">
                        <td className="px-3 py-2 text-slate-500 whitespace-nowrap">
                          {new Date(log.created_at).toLocaleString("en-UG")}
                        </td>
                        <td className="px-3 py-2 font-semibold text-slate-800">{log.user_name}</td>
                        <td className="px-3 py-2">
                          <span
                            className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${log.user_role === "Administrator" ? "bg-amber-100 text-amber-800" : "bg-blue-100 text-blue-800"}`}
                          >
                            {log.user_role}
                          </span>
                        </td>
                        <td className="px-3 py-2 font-semibold text-slate-800">{log.action}</td>
                        <td className="px-3 py-2 text-slate-500">{log.module}</td>
                        <td className="px-3 py-2 font-mono text-chetu-blue">
                          {log.record_id || "—"}
                        </td>
                        <td className="px-3 py-2 font-mono text-slate-500">{log.ip_address}</td>
                        <td
                          className="px-3 py-2 text-slate-400 max-w-[160px] truncate"
                          title={log.device_info || ""}
                        >
                          {log.device_info ? log.device_info.substring(0, 28) + "…" : "—"}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </TableScroll>
          </div>
        </div>
      )}

      {/* ════════════════════════════════════════
          REPORTS TAB
      ════════════════════════════════════════ */}
      {activeTab === "reports" && (
        <div className="space-y-5">
          <div className="bg-gradient-to-r from-chetu-navy to-chetu-blue rounded-2xl p-5 text-white">
            <h2 className="text-base font-black flex items-center gap-2">
              <Printer className="w-5 h-5" />
              Auditor Report Center
            </h2>
            <p className="text-xs text-blue-200 mt-1">
              Generate branded, numbered audit reports with Chetu Microfinance header, generated-by
              details, and professional page numbers.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {[
              {
                title: "Financial Summary",
                desc: "Disbursements, collections, balance, fees, interest & net portfolio.",
                icon: DollarSign,
                color: "text-chetu-blue",
                bg: "bg-blue-50",
                actions: [
                  { label: "PDF", fn: pdfFinancial, cls: "bg-chetu-blue hover:bg-chetu-darkblue" },
                ],
              },
              {
                title: "Monthly Financial Stmt",
                desc: "Complete monthly P&L statement with all key financial indicators.",
                icon: FileText,
                color: "text-indigo-600",
                bg: "bg-indigo-50",
                actions: [
                  {
                    label: "PDF",
                    fn: pdfMonthlyStatement,
                    cls: "bg-indigo-600 hover:bg-indigo-700",
                  },
                ],
              },
              {
                title: "Loan Portfolio Report",
                desc: "Full loan register — active, paid, overdue & defaulted loans.",
                icon: FileSpreadsheet,
                color: "text-sky-600",
                bg: "bg-sky-50",
                actions: [
                  { label: "PDF", fn: pdfLoanAudit, cls: "bg-chetu-blue hover:bg-chetu-darkblue" },
                  { label: "CSV", fn: csvLoans, cls: "bg-emerald-600 hover:bg-emerald-700" },
                ],
              },
              {
                title: "Collections Report",
                desc: "Daily, weekly, monthly totals with full repayment history by officer.",
                icon: CheckCircle2,
                color: "text-emerald-600",
                bg: "bg-emerald-50",
                actions: [
                  { label: "PDF", fn: pdfCollections, cls: "bg-emerald-600 hover:bg-emerald-700" },
                ],
              },
              {
                title: "Repayment Audit Report",
                desc: "Detailed repayment register with receipt numbers, methods and officer notes.",
                icon: Receipt,
                color: "text-teal-600",
                bg: "bg-teal-50",
                actions: [{ label: "PDF", fn: pdfRepayment, cls: "bg-teal-600 hover:bg-teal-700" }],
              },
              {
                title: "Cash Flow Report",
                desc: "Monthly inflows, outflows, and net cash position across the portfolio.",
                icon: TrendingUp,
                color: "text-cyan-600",
                bg: "bg-cyan-50",
                actions: [{ label: "PDF", fn: pdfCashFlow, cls: "bg-cyan-600 hover:bg-cyan-700" }],
              },
              {
                title: "Expense Audit Report",
                desc: "Full expense ledger with categories, monthly totals & voucher references.",
                icon: CreditCard,
                color: "text-red-600",
                bg: "bg-red-50",
                actions: [
                  { label: "PDF", fn: pdfExpense, cls: "bg-red-600 hover:bg-red-700" },
                  { label: "CSV", fn: csvExpenses, cls: "bg-emerald-600 hover:bg-emerald-700" },
                ],
              },
              {
                title: "Bank Transactions",
                desc: "Complete deposit & withdrawal history with running balances and references.",
                icon: Banknote,
                color: "text-purple-600",
                bg: "bg-purple-50",
                actions: [{ label: "PDF", fn: pdfBank, cls: "bg-purple-600 hover:bg-purple-700" }],
              },
              {
                title: "User Activity Trail",
                desc: "Immutable system log — logins, actions, approvals, disbursements, settings changes.",
                icon: Activity,
                color: "text-amber-600",
                bg: "bg-amber-50",
                actions: [
                  { label: "PDF", fn: pdfActivity, cls: "bg-amber-600 hover:bg-amber-700" },
                  { label: "CSV", fn: csvActivity, cls: "bg-emerald-600 hover:bg-emerald-700" },
                ],
              },
              {
                title: "Audit Trail Report",
                desc: "Full chronological audit trail with all system events and user actions.",
                icon: ShieldAlert,
                color: "text-slate-700",
                bg: "bg-slate-100",
                actions: [
                  { label: "PDF", fn: pdfActivity, cls: "bg-slate-700 hover:bg-slate-800" },
                ],
              },
              {
                title: "Reconciliation Report",
                desc: "Automated cross-check of deposits, collections, withdrawals, expenses & bank balance.",
                icon: Scale,
                color: isReconciled ? "text-emerald-600" : "text-red-600",
                bg: isReconciled ? "bg-emerald-50" : "bg-red-50",
                actions: [
                  {
                    label: "PDF",
                    fn: pdfReconciliation,
                    cls: isReconciled
                      ? "bg-emerald-600 hover:bg-emerald-700"
                      : "bg-red-600 hover:bg-red-700",
                  },
                ],
              },
            ].map((report) => (
              <div
                key={report.title}
                className="bg-white rounded-2xl border border-slate-200 p-4 flex flex-col justify-between hover:shadow-md transition-shadow"
              >
                <div>
                  <div className={`inline-flex p-2.5 rounded-xl ${report.bg} mb-3`}>
                    <report.icon className={`w-5 h-5 ${report.color}`} />
                  </div>
                  <h3 className="text-sm font-black text-slate-800 leading-tight">
                    {report.title}
                  </h3>
                  <p className="text-xs text-slate-500 mt-1.5 leading-relaxed">{report.desc}</p>
                </div>
                <div className="flex gap-2 mt-4 pt-3 border-t border-slate-100">
                  {report.actions.map((action) => (
                    <button
                      key={action.label}
                      onClick={action.fn}
                      className={`flex items-center gap-1.5 px-3 py-2 text-white rounded-xl text-[11px] font-bold transition-colors ${action.cls}`}
                    >
                      <Download className="w-3 h-3" />
                      {action.label}
                    </button>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className="bg-slate-50 border border-slate-200 rounded-2xl p-4 text-xs text-slate-500">
            <p className="font-bold text-slate-700 mb-2 flex items-center gap-1.5">
              <Eye className="w-3.5 h-3.5 text-chetu-blue" />
              Every Report Includes:
            </p>
            <ul className="list-disc list-inside space-y-1">
              <li>Chetu Microfinance Ltd corporate header with Kampala HQ contact details</li>
              <li>Unique audit reference number (e.g. AUD-2026-4821)</li>
              <li>
                Generation date and <em>Generated By</em> officer name
              </li>
              <li>Confidentiality notice on each page</li>
              <li>
                Professional page numbering: <strong>Page X of Y</strong>
              </li>
            </ul>
          </div>
        </div>
      )}
    </div>
  );
};
