/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmissionSalesRouteImport } from './routes/admission-sales'
import { Route as AdvanceCollectionRouteImport } from './routes/advance-collection'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as BadDebtsCollectionRouteImport } from './routes/bad-debts-collection'
import { Route as BadLoansRouteImport } from './routes/bad-loans'
import { Route as BankManagementRouteImport } from './routes/bank-management'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ClientGroupsRouteImport } from './routes/client-groups'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as GroupCollectionRouteImport } from './routes/group-collection'
import { Route as GroupCreateRouteImport } from './routes/group-create'
import { Route as LoanApplicationsRouteImport } from './routes/loan-applications'
import { Route as LoanProductsRouteImport } from './routes/loan-products'
import { Route as LoanRejectedRouteImport } from './routes/loan-rejected'
import { Route as LoanRollbackRouteImport } from './routes/loan-rollback'
import { Route as LoanSettlementRouteImport } from './routes/loan-settlement'
import { Route as LoanWaitingApprovalRouteImport } from './routes/loan-waiting-approval'
import { Route as LoanWaitingDisburseRouteImport } from './routes/loan-waiting-disburse'
import { Route as LoanWriteoffRouteImport } from './routes/loan-writeoff'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemberAdmissionRouteImport } from './routes/member-admission'
import { Route as MemberDeathApplicationRouteImport } from './routes/member-death-application'
import { Route as MemberDeathListRouteImport } from './routes/member-death-list'
import { Route as MemberInactiveRouteImport } from './routes/member-inactive'
import { Route as MemberListRouteImport } from './routes/member-list'
import { Route as MemberRejectedRouteImport } from './routes/member-rejected'
import { Route as MemberWaitingApprovalRouteImport } from './routes/member-waiting-approval'
import { Route as OverdueCollectionRouteImport } from './routes/overdue-collection'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RepaymentsRouteImport } from './routes/repayments'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SavingsAccountsRouteImport } from './routes/savings-accounts'
import { Route as SecurityReturnsRouteImport } from './routes/security-returns'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsersRouteImport } from './routes/users'
import { Route as GroupsRejectedRouteImport } from './routes/groups.rejected'
import { Route as GroupsWaitingApprovalRouteImport } from './routes/groups.waiting-approval'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsApprovalsRouteImport } from './routes/reports.approvals'
import { Route as ReportsDailyOverdueRouteImport } from './routes/reports.daily-overdue'
import { Route as ReportsDayCollectionListRouteImport } from './routes/reports.day-collection-list'
import { Route as ReportsFeeCollectionRouteImport } from './routes/reports.fee-collection'
import { Route as ReportsLoWiseGroupRealizableRouteImport } from './routes/reports.lo-wise-group-realizable'
import { Route as ReportsLoanClosureRouteImport } from './routes/reports.loan-closure'
import { Route as ReportsMasterRollRouteImport } from './routes/reports.master-roll'
import { Route as ReportsOutstandingRouteImport } from './routes/reports.outstanding'
import { Route as ReportsOverdueCollectionListRouteImport } from './routes/reports.overdue-collection-list'
import { Route as ReportsParRouteImport } from './routes/reports.par'
import { Route as ReportsReversalsRouteImport } from './routes/reports.reversals'
import { Route as ReportsSavingsRouteImport } from './routes/reports.savings'
import { Route as TransfersGroupInterchangeRouteImport } from './routes/transfers.group-interchange'
import { Route as TransfersGroupOfficerRouteImport } from './routes/transfers.group-officer'
import { Route as TransfersMemberRouteImport } from './routes/transfers.member'
import { Route as TransfersReceiveRouteImport } from './routes/transfers.receive'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionSalesRoute = AdmissionSalesRouteImport.update({
  id: '/admission-sales',
  path: '/admission-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvanceCollectionRoute = AdvanceCollectionRouteImport.update({
  id: '/advance-collection',
  path: '/advance-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BadDebtsCollectionRoute = BadDebtsCollectionRouteImport.update({
  id: '/bad-debts-collection',
  path: '/bad-debts-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const BadLoansRoute = BadLoansRouteImport.update({
  id: '/bad-loans',
  path: '/bad-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const BankManagementRoute = BankManagementRouteImport.update({
  id: '/bank-management',
  path: '/bank-management',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientGroupsRoute = ClientGroupsRouteImport.update({
  id: '/client-groups',
  path: '/client-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupCollectionRoute = GroupCollectionRouteImport.update({
  id: '/group-collection',
  path: '/group-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupCreateRoute = GroupCreateRouteImport.update({
  id: '/group-create',
  path: '/group-create',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanApplicationsRoute = LoanApplicationsRouteImport.update({
  id: '/loan-applications',
  path: '/loan-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanProductsRoute = LoanProductsRouteImport.update({
  id: '/loan-products',
  path: '/loan-products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanRejectedRoute = LoanRejectedRouteImport.update({
  id: '/loan-rejected',
  path: '/loan-rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanRollbackRoute = LoanRollbackRouteImport.update({
  id: '/loan-rollback',
  path: '/loan-rollback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanSettlementRoute = LoanSettlementRouteImport.update({
  id: '/loan-settlement',
  path: '/loan-settlement',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanWaitingApprovalRoute = LoanWaitingApprovalRouteImport.update({
  id: '/loan-waiting-approval',
  path: '/loan-waiting-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanWaitingDisburseRoute = LoanWaitingDisburseRouteImport.update({
  id: '/loan-waiting-disburse',
  path: '/loan-waiting-disburse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanWriteoffRoute = LoanWriteoffRouteImport.update({
  id: '/loan-writeoff',
  path: '/loan-writeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberAdmissionRoute = MemberAdmissionRouteImport.update({
  id: '/member-admission',
  path: '/member-admission',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberDeathApplicationRoute = MemberDeathApplicationRouteImport.update({
  id: '/member-death-application',
  path: '/member-death-application',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberDeathListRoute = MemberDeathListRouteImport.update({
  id: '/member-death-list',
  path: '/member-death-list',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberInactiveRoute = MemberInactiveRouteImport.update({
  id: '/member-inactive',
  path: '/member-inactive',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberListRoute = MemberListRouteImport.update({
  id: '/member-list',
  path: '/member-list',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRejectedRoute = MemberRejectedRouteImport.update({
  id: '/member-rejected',
  path: '/member-rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberWaitingApprovalRoute = MemberWaitingApprovalRouteImport.update({
  id: '/member-waiting-approval',
  path: '/member-waiting-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const OverdueCollectionRoute = OverdueCollectionRouteImport.update({
  id: '/overdue-collection',
  path: '/overdue-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RepaymentsRoute = RepaymentsRouteImport.update({
  id: '/repayments',
  path: '/repayments',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsAccountsRoute = SavingsAccountsRouteImport.update({
  id: '/savings-accounts',
  path: '/savings-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityReturnsRoute = SecurityReturnsRouteImport.update({
  id: '/security-returns',
  path: '/security-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRejectedRoute = GroupsRejectedRouteImport.update({
  id: '/groups/rejected',
  path: '/groups/rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsWaitingApprovalRoute = GroupsWaitingApprovalRouteImport.update({
  id: '/groups/waiting-approval',
  path: '/groups/waiting-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsApprovalsRoute = ReportsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsDailyOverdueRoute = ReportsDailyOverdueRouteImport.update({
  id: '/daily-overdue',
  path: '/daily-overdue',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsDayCollectionListRoute =
  ReportsDayCollectionListRouteImport.update({
    id: '/day-collection-list',
    path: '/day-collection-list',
    getParentRoute: () => ReportsRoute,
  } as any)
const ReportsFeeCollectionRoute = ReportsFeeCollectionRouteImport.update({
  id: '/fee-collection',
  path: '/fee-collection',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsLoWiseGroupRealizableRoute =
  ReportsLoWiseGroupRealizableRouteImport.update({
    id: '/lo-wise-group-realizable',
    path: '/lo-wise-group-realizable',
    getParentRoute: () => ReportsRoute,
  } as any)
const ReportsLoanClosureRoute = ReportsLoanClosureRouteImport.update({
  id: '/loan-closure',
  path: '/loan-closure',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsMasterRollRoute = ReportsMasterRollRouteImport.update({
  id: '/master-roll',
  path: '/master-roll',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsOutstandingRoute = ReportsOutstandingRouteImport.update({
  id: '/outstanding',
  path: '/outstanding',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsOverdueCollectionListRoute =
  ReportsOverdueCollectionListRouteImport.update({
    id: '/overdue-collection-list',
    path: '/overdue-collection-list',
    getParentRoute: () => ReportsRoute,
  } as any)
const ReportsParRoute = ReportsParRouteImport.update({
  id: '/par',
  path: '/par',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsReversalsRoute = ReportsReversalsRouteImport.update({
  id: '/reversals',
  path: '/reversals',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSavingsRoute = ReportsSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => ReportsRoute,
} as any)
const TransfersGroupInterchangeRoute =
  TransfersGroupInterchangeRouteImport.update({
    id: '/transfers/group-interchange',
    path: '/transfers/group-interchange',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransfersGroupOfficerRoute = TransfersGroupOfficerRouteImport.update({
  id: '/transfers/group-officer',
  path: '/transfers/group-officer',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersMemberRoute = TransfersMemberRouteImport.update({
  id: '/transfers/member',
  path: '/transfers/member',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersReceiveRoute = TransfersReceiveRouteImport.update({
  id: '/transfers/receive',
  path: '/transfers/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admission-sales': typeof AdmissionSalesRoute
  '/advance-collection': typeof AdvanceCollectionRoute
  '/audit': typeof AuditRoute
  '/audit-logs': typeof AuditLogsRoute
  '/bad-debts-collection': typeof BadDebtsCollectionRoute
  '/bad-loans': typeof BadLoansRoute
  '/bank-management': typeof BankManagementRoute
  '/branches': typeof BranchesRoute
  '/calculator': typeof CalculatorRoute
  '/client-groups': typeof ClientGroupsRoute
  '/clients': typeof ClientsRoute
  '/expenses': typeof ExpensesRoute
  '/group-collection': typeof GroupCollectionRoute
  '/group-create': typeof GroupCreateRoute
  '/loan-applications': typeof LoanApplicationsRoute
  '/loan-products': typeof LoanProductsRoute
  '/loan-rejected': typeof LoanRejectedRoute
  '/loan-rollback': typeof LoanRollbackRoute
  '/loan-settlement': typeof LoanSettlementRoute
  '/loan-waiting-approval': typeof LoanWaitingApprovalRoute
  '/loan-waiting-disburse': typeof LoanWaitingDisburseRoute
  '/loan-writeoff': typeof LoanWriteoffRoute
  '/login': typeof LoginRoute
  '/member-admission': typeof MemberAdmissionRoute
  '/member-death-application': typeof MemberDeathApplicationRoute
  '/member-death-list': typeof MemberDeathListRoute
  '/member-inactive': typeof MemberInactiveRoute
  '/member-list': typeof MemberListRoute
  '/member-rejected': typeof MemberRejectedRoute
  '/member-waiting-approval': typeof MemberWaitingApprovalRoute
  '/overdue-collection': typeof OverdueCollectionRoute
  '/profile': typeof ProfileRoute
  '/repayments': typeof RepaymentsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/savings': typeof SavingsRoute
  '/savings-accounts': typeof SavingsAccountsRoute
  '/security-returns': typeof SecurityReturnsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/groups/rejected': typeof GroupsRejectedRoute
  '/groups/waiting-approval': typeof GroupsWaitingApprovalRoute
  '/reports/approvals': typeof ReportsApprovalsRoute
  '/reports/daily-overdue': typeof ReportsDailyOverdueRoute
  '/reports/day-collection-list': typeof ReportsDayCollectionListRoute
  '/reports/fee-collection': typeof ReportsFeeCollectionRoute
  '/reports/lo-wise-group-realizable': typeof ReportsLoWiseGroupRealizableRoute
  '/reports/loan-closure': typeof ReportsLoanClosureRoute
  '/reports/master-roll': typeof ReportsMasterRollRoute
  '/reports/outstanding': typeof ReportsOutstandingRoute
  '/reports/overdue-collection-list': typeof ReportsOverdueCollectionListRoute
  '/reports/par': typeof ReportsParRoute
  '/reports/reversals': typeof ReportsReversalsRoute
  '/reports/savings': typeof ReportsSavingsRoute
  '/transfers/group-interchange': typeof TransfersGroupInterchangeRoute
  '/transfers/group-officer': typeof TransfersGroupOfficerRoute
  '/transfers/member': typeof TransfersMemberRoute
  '/transfers/receive': typeof TransfersReceiveRoute
  '/reports/': typeof ReportsIndexRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admission-sales': typeof AdmissionSalesRoute
  '/advance-collection': typeof AdvanceCollectionRoute
  '/audit': typeof AuditRoute
  '/audit-logs': typeof AuditLogsRoute
  '/bad-debts-collection': typeof BadDebtsCollectionRoute
  '/bad-loans': typeof BadLoansRoute
  '/bank-management': typeof BankManagementRoute
  '/branches': typeof BranchesRoute
  '/calculator': typeof CalculatorRoute
  '/client-groups': typeof ClientGroupsRoute
  '/clients': typeof ClientsRoute
  '/expenses': typeof ExpensesRoute
  '/group-collection': typeof GroupCollectionRoute
  '/group-create': typeof GroupCreateRoute
  '/loan-applications': typeof LoanApplicationsRoute
  '/loan-products': typeof LoanProductsRoute
  '/loan-rejected': typeof LoanRejectedRoute
  '/loan-rollback': typeof LoanRollbackRoute
  '/loan-settlement': typeof LoanSettlementRoute
  '/loan-waiting-approval': typeof LoanWaitingApprovalRoute
  '/loan-waiting-disburse': typeof LoanWaitingDisburseRoute
  '/loan-writeoff': typeof LoanWriteoffRoute
  '/login': typeof LoginRoute
  '/member-admission': typeof MemberAdmissionRoute
  '/member-death-application': typeof MemberDeathApplicationRoute
  '/member-death-list': typeof MemberDeathListRoute
  '/member-inactive': typeof MemberInactiveRoute
  '/member-list': typeof MemberListRoute
  '/member-rejected': typeof MemberRejectedRoute
  '/member-waiting-approval': typeof MemberWaitingApprovalRoute
  '/overdue-collection': typeof OverdueCollectionRoute
  '/profile': typeof ProfileRoute
  '/repayments': typeof RepaymentsRoute
  '/savings': typeof SavingsRoute
  '/savings-accounts': typeof SavingsAccountsRoute
  '/security-returns': typeof SecurityReturnsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/groups/rejected': typeof GroupsRejectedRoute
  '/groups/waiting-approval': typeof GroupsWaitingApprovalRoute
  '/reports/approvals': typeof ReportsApprovalsRoute
  '/reports/daily-overdue': typeof ReportsDailyOverdueRoute
  '/reports/day-collection-list': typeof ReportsDayCollectionListRoute
  '/reports/fee-collection': typeof ReportsFeeCollectionRoute
  '/reports/lo-wise-group-realizable': typeof ReportsLoWiseGroupRealizableRoute
  '/reports/loan-closure': typeof ReportsLoanClosureRoute
  '/reports/master-roll': typeof ReportsMasterRollRoute
  '/reports/outstanding': typeof ReportsOutstandingRoute
  '/reports/overdue-collection-list': typeof ReportsOverdueCollectionListRoute
  '/reports/par': typeof ReportsParRoute
  '/reports/reversals': typeof ReportsReversalsRoute
  '/reports/savings': typeof ReportsSavingsRoute
  '/transfers/group-interchange': typeof TransfersGroupInterchangeRoute
  '/transfers/group-officer': typeof TransfersGroupOfficerRoute
  '/transfers/member': typeof TransfersMemberRoute
  '/transfers/receive': typeof TransfersReceiveRoute
  '/reports': typeof ReportsIndexRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admission-sales': typeof AdmissionSalesRoute
  '/advance-collection': typeof AdvanceCollectionRoute
  '/audit': typeof AuditRoute
  '/audit-logs': typeof AuditLogsRoute
  '/bad-debts-collection': typeof BadDebtsCollectionRoute
  '/bad-loans': typeof BadLoansRoute
  '/bank-management': typeof BankManagementRoute
  '/branches': typeof BranchesRoute
  '/calculator': typeof CalculatorRoute
  '/client-groups': typeof ClientGroupsRoute
  '/clients': typeof ClientsRoute
  '/expenses': typeof ExpensesRoute
  '/group-collection': typeof GroupCollectionRoute
  '/group-create': typeof GroupCreateRoute
  '/loan-applications': typeof LoanApplicationsRoute
  '/loan-products': typeof LoanProductsRoute
  '/loan-rejected': typeof LoanRejectedRoute
  '/loan-rollback': typeof LoanRollbackRoute
  '/loan-settlement': typeof LoanSettlementRoute
  '/loan-waiting-approval': typeof LoanWaitingApprovalRoute
  '/loan-waiting-disburse': typeof LoanWaitingDisburseRoute
  '/loan-writeoff': typeof LoanWriteoffRoute
  '/login': typeof LoginRoute
  '/member-admission': typeof MemberAdmissionRoute
  '/member-death-application': typeof MemberDeathApplicationRoute
  '/member-death-list': typeof MemberDeathListRoute
  '/member-inactive': typeof MemberInactiveRoute
  '/member-list': typeof MemberListRoute
  '/member-rejected': typeof MemberRejectedRoute
  '/member-waiting-approval': typeof MemberWaitingApprovalRoute
  '/overdue-collection': typeof OverdueCollectionRoute
  '/profile': typeof ProfileRoute
  '/repayments': typeof RepaymentsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/savings': typeof SavingsRoute
  '/savings-accounts': typeof SavingsAccountsRoute
  '/security-returns': typeof SecurityReturnsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/groups/rejected': typeof GroupsRejectedRoute
  '/groups/waiting-approval': typeof GroupsWaitingApprovalRoute
  '/reports/approvals': typeof ReportsApprovalsRoute
  '/reports/daily-overdue': typeof ReportsDailyOverdueRoute
  '/reports/day-collection-list': typeof ReportsDayCollectionListRoute
  '/reports/fee-collection': typeof ReportsFeeCollectionRoute
  '/reports/lo-wise-group-realizable': typeof ReportsLoWiseGroupRealizableRoute
  '/reports/loan-closure': typeof ReportsLoanClosureRoute
  '/reports/master-roll': typeof ReportsMasterRollRoute
  '/reports/outstanding': typeof ReportsOutstandingRoute
  '/reports/overdue-collection-list': typeof ReportsOverdueCollectionListRoute
  '/reports/par': typeof ReportsParRoute
  '/reports/reversals': typeof ReportsReversalsRoute
  '/reports/savings': typeof ReportsSavingsRoute
  '/transfers/group-interchange': typeof TransfersGroupInterchangeRoute
  '/transfers/group-officer': typeof TransfersGroupOfficerRoute
  '/transfers/member': typeof TransfersMemberRoute
  '/transfers/receive': typeof TransfersReceiveRoute
  '/reports/': typeof ReportsIndexRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admission-sales'
    | '/advance-collection'
    | '/audit'
    | '/audit-logs'
    | '/bad-debts-collection'
    | '/bad-loans'
    | '/bank-management'
    | '/branches'
    | '/calculator'
    | '/client-groups'
    | '/clients'
    | '/expenses'
    | '/group-collection'
    | '/group-create'
    | '/loan-applications'
    | '/loan-products'
    | '/loan-rejected'
    | '/loan-rollback'
    | '/loan-settlement'
    | '/loan-waiting-approval'
    | '/loan-waiting-disburse'
    | '/loan-writeoff'
    | '/login'
    | '/member-admission'
    | '/member-death-application'
    | '/member-death-list'
    | '/member-inactive'
    | '/member-list'
    | '/member-rejected'
    | '/member-waiting-approval'
    | '/overdue-collection'
    | '/profile'
    | '/repayments'
    | '/reports'
    | '/savings'
    | '/savings-accounts'
    | '/security-returns'
    | '/settings'
    | '/users'
    | '/groups/rejected'
    | '/groups/waiting-approval'
    | '/reports/approvals'
    | '/reports/daily-overdue'
    | '/reports/day-collection-list'
    | '/reports/fee-collection'
    | '/reports/lo-wise-group-realizable'
    | '/reports/loan-closure'
    | '/reports/master-roll'
    | '/reports/outstanding'
    | '/reports/overdue-collection-list'
    | '/reports/par'
    | '/reports/reversals'
    | '/reports/savings'
    | '/transfers/group-interchange'
    | '/transfers/group-officer'
    | '/transfers/member'
    | '/transfers/receive'
    | '/reports/'
    | '/api/public/bootstrap-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admission-sales'
    | '/advance-collection'
    | '/audit'
    | '/audit-logs'
    | '/bad-debts-collection'
    | '/bad-loans'
    | '/bank-management'
    | '/branches'
    | '/calculator'
    | '/client-groups'
    | '/clients'
    | '/expenses'
    | '/group-collection'
    | '/group-create'
    | '/loan-applications'
    | '/loan-products'
    | '/loan-rejected'
    | '/loan-rollback'
    | '/loan-settlement'
    | '/loan-waiting-approval'
    | '/loan-waiting-disburse'
    | '/loan-writeoff'
    | '/login'
    | '/member-admission'
    | '/member-death-application'
    | '/member-death-list'
    | '/member-inactive'
    | '/member-list'
    | '/member-rejected'
    | '/member-waiting-approval'
    | '/overdue-collection'
    | '/profile'
    | '/repayments'
    | '/savings'
    | '/savings-accounts'
    | '/security-returns'
    | '/settings'
    | '/users'
    | '/groups/rejected'
    | '/groups/waiting-approval'
    | '/reports/approvals'
    | '/reports/daily-overdue'
    | '/reports/day-collection-list'
    | '/reports/fee-collection'
    | '/reports/lo-wise-group-realizable'
    | '/reports/loan-closure'
    | '/reports/master-roll'
    | '/reports/outstanding'
    | '/reports/overdue-collection-list'
    | '/reports/par'
    | '/reports/reversals'
    | '/reports/savings'
    | '/transfers/group-interchange'
    | '/transfers/group-officer'
    | '/transfers/member'
    | '/transfers/receive'
    | '/reports'
    | '/api/public/bootstrap-admin'
  id:
    | '__root__'
    | '/'
    | '/admission-sales'
    | '/advance-collection'
    | '/audit'
    | '/audit-logs'
    | '/bad-debts-collection'
    | '/bad-loans'
    | '/bank-management'
    | '/branches'
    | '/calculator'
    | '/client-groups'
    | '/clients'
    | '/expenses'
    | '/group-collection'
    | '/group-create'
    | '/loan-applications'
    | '/loan-products'
    | '/loan-rejected'
    | '/loan-rollback'
    | '/loan-settlement'
    | '/loan-waiting-approval'
    | '/loan-waiting-disburse'
    | '/loan-writeoff'
    | '/login'
    | '/member-admission'
    | '/member-death-application'
    | '/member-death-list'
    | '/member-inactive'
    | '/member-list'
    | '/member-rejected'
    | '/member-waiting-approval'
    | '/overdue-collection'
    | '/profile'
    | '/repayments'
    | '/reports'
    | '/savings'
    | '/savings-accounts'
    | '/security-returns'
    | '/settings'
    | '/users'
    | '/groups/rejected'
    | '/groups/waiting-approval'
    | '/reports/approvals'
    | '/reports/daily-overdue'
    | '/reports/day-collection-list'
    | '/reports/fee-collection'
    | '/reports/lo-wise-group-realizable'
    | '/reports/loan-closure'
    | '/reports/master-roll'
    | '/reports/outstanding'
    | '/reports/overdue-collection-list'
    | '/reports/par'
    | '/reports/reversals'
    | '/reports/savings'
    | '/transfers/group-interchange'
    | '/transfers/group-officer'
    | '/transfers/member'
    | '/transfers/receive'
    | '/reports/'
    | '/api/public/bootstrap-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionSalesRoute: typeof AdmissionSalesRoute
  AdvanceCollectionRoute: typeof AdvanceCollectionRoute
  AuditRoute: typeof AuditRoute
  AuditLogsRoute: typeof AuditLogsRoute
  BadDebtsCollectionRoute: typeof BadDebtsCollectionRoute
  BadLoansRoute: typeof BadLoansRoute
  BankManagementRoute: typeof BankManagementRoute
  BranchesRoute: typeof BranchesRoute
  CalculatorRoute: typeof CalculatorRoute
  ClientGroupsRoute: typeof ClientGroupsRoute
  ClientsRoute: typeof ClientsRoute
  ExpensesRoute: typeof ExpensesRoute
  GroupCollectionRoute: typeof GroupCollectionRoute
  GroupCreateRoute: typeof GroupCreateRoute
  LoanApplicationsRoute: typeof LoanApplicationsRoute
  LoanProductsRoute: typeof LoanProductsRoute
  LoanRejectedRoute: typeof LoanRejectedRoute
  LoanRollbackRoute: typeof LoanRollbackRoute
  LoanSettlementRoute: typeof LoanSettlementRoute
  LoanWaitingApprovalRoute: typeof LoanWaitingApprovalRoute
  LoanWaitingDisburseRoute: typeof LoanWaitingDisburseRoute
  LoanWriteoffRoute: typeof LoanWriteoffRoute
  LoginRoute: typeof LoginRoute
  MemberAdmissionRoute: typeof MemberAdmissionRoute
  MemberDeathApplicationRoute: typeof MemberDeathApplicationRoute
  MemberDeathListRoute: typeof MemberDeathListRoute
  MemberInactiveRoute: typeof MemberInactiveRoute
  MemberListRoute: typeof MemberListRoute
  MemberRejectedRoute: typeof MemberRejectedRoute
  MemberWaitingApprovalRoute: typeof MemberWaitingApprovalRoute
  OverdueCollectionRoute: typeof OverdueCollectionRoute
  ProfileRoute: typeof ProfileRoute
  RepaymentsRoute: typeof RepaymentsRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SavingsRoute: typeof SavingsRoute
  SavingsAccountsRoute: typeof SavingsAccountsRoute
  SecurityReturnsRoute: typeof SecurityReturnsRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  GroupsRejectedRoute: typeof GroupsRejectedRoute
  GroupsWaitingApprovalRoute: typeof GroupsWaitingApprovalRoute
  TransfersGroupInterchangeRoute: typeof TransfersGroupInterchangeRoute
  TransfersGroupOfficerRoute: typeof TransfersGroupOfficerRoute
  TransfersMemberRoute: typeof TransfersMemberRoute
  TransfersReceiveRoute: typeof TransfersReceiveRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission-sales': {
      id: '/admission-sales'
      path: '/admission-sales'
      fullPath: '/admission-sales'
      preLoaderRoute: typeof AdmissionSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advance-collection': {
      id: '/advance-collection'
      path: '/advance-collection'
      fullPath: '/advance-collection'
      preLoaderRoute: typeof AdvanceCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bad-debts-collection': {
      id: '/bad-debts-collection'
      path: '/bad-debts-collection'
      fullPath: '/bad-debts-collection'
      preLoaderRoute: typeof BadDebtsCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bad-loans': {
      id: '/bad-loans'
      path: '/bad-loans'
      fullPath: '/bad-loans'
      preLoaderRoute: typeof BadLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-management': {
      id: '/bank-management'
      path: '/bank-management'
      fullPath: '/bank-management'
      preLoaderRoute: typeof BankManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-groups': {
      id: '/client-groups'
      path: '/client-groups'
      fullPath: '/client-groups'
      preLoaderRoute: typeof ClientGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-collection': {
      id: '/group-collection'
      path: '/group-collection'
      fullPath: '/group-collection'
      preLoaderRoute: typeof GroupCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-create': {
      id: '/group-create'
      path: '/group-create'
      fullPath: '/group-create'
      preLoaderRoute: typeof GroupCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-applications': {
      id: '/loan-applications'
      path: '/loan-applications'
      fullPath: '/loan-applications'
      preLoaderRoute: typeof LoanApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-products': {
      id: '/loan-products'
      path: '/loan-products'
      fullPath: '/loan-products'
      preLoaderRoute: typeof LoanProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-rejected': {
      id: '/loan-rejected'
      path: '/loan-rejected'
      fullPath: '/loan-rejected'
      preLoaderRoute: typeof LoanRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-rollback': {
      id: '/loan-rollback'
      path: '/loan-rollback'
      fullPath: '/loan-rollback'
      preLoaderRoute: typeof LoanRollbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-settlement': {
      id: '/loan-settlement'
      path: '/loan-settlement'
      fullPath: '/loan-settlement'
      preLoaderRoute: typeof LoanSettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-waiting-approval': {
      id: '/loan-waiting-approval'
      path: '/loan-waiting-approval'
      fullPath: '/loan-waiting-approval'
      preLoaderRoute: typeof LoanWaitingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-waiting-disburse': {
      id: '/loan-waiting-disburse'
      path: '/loan-waiting-disburse'
      fullPath: '/loan-waiting-disburse'
      preLoaderRoute: typeof LoanWaitingDisburseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-writeoff': {
      id: '/loan-writeoff'
      path: '/loan-writeoff'
      fullPath: '/loan-writeoff'
      preLoaderRoute: typeof LoanWriteoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-admission': {
      id: '/member-admission'
      path: '/member-admission'
      fullPath: '/member-admission'
      preLoaderRoute: typeof MemberAdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-death-application': {
      id: '/member-death-application'
      path: '/member-death-application'
      fullPath: '/member-death-application'
      preLoaderRoute: typeof MemberDeathApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-death-list': {
      id: '/member-death-list'
      path: '/member-death-list'
      fullPath: '/member-death-list'
      preLoaderRoute: typeof MemberDeathListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-inactive': {
      id: '/member-inactive'
      path: '/member-inactive'
      fullPath: '/member-inactive'
      preLoaderRoute: typeof MemberInactiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-list': {
      id: '/member-list'
      path: '/member-list'
      fullPath: '/member-list'
      preLoaderRoute: typeof MemberListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-rejected': {
      id: '/member-rejected'
      path: '/member-rejected'
      fullPath: '/member-rejected'
      preLoaderRoute: typeof MemberRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-waiting-approval': {
      id: '/member-waiting-approval'
      path: '/member-waiting-approval'
      fullPath: '/member-waiting-approval'
      preLoaderRoute: typeof MemberWaitingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overdue-collection': {
      id: '/overdue-collection'
      path: '/overdue-collection'
      fullPath: '/overdue-collection'
      preLoaderRoute: typeof OverdueCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repayments': {
      id: '/repayments'
      path: '/repayments'
      fullPath: '/repayments'
      preLoaderRoute: typeof RepaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings-accounts': {
      id: '/savings-accounts'
      path: '/savings-accounts'
      fullPath: '/savings-accounts'
      preLoaderRoute: typeof SavingsAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-returns': {
      id: '/security-returns'
      path: '/security-returns'
      fullPath: '/security-returns'
      preLoaderRoute: typeof SecurityReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/rejected': {
      id: '/groups/rejected'
      path: '/groups/rejected'
      fullPath: '/groups/rejected'
      preLoaderRoute: typeof GroupsRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/waiting-approval': {
      id: '/groups/waiting-approval'
      path: '/groups/waiting-approval'
      fullPath: '/groups/waiting-approval'
      preLoaderRoute: typeof GroupsWaitingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/approvals': {
      id: '/reports/approvals'
      path: '/approvals'
      fullPath: '/reports/approvals'
      preLoaderRoute: typeof ReportsApprovalsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/daily-overdue': {
      id: '/reports/daily-overdue'
      path: '/daily-overdue'
      fullPath: '/reports/daily-overdue'
      preLoaderRoute: typeof ReportsDailyOverdueRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/day-collection-list': {
      id: '/reports/day-collection-list'
      path: '/day-collection-list'
      fullPath: '/reports/day-collection-list'
      preLoaderRoute: typeof ReportsDayCollectionListRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/fee-collection': {
      id: '/reports/fee-collection'
      path: '/fee-collection'
      fullPath: '/reports/fee-collection'
      preLoaderRoute: typeof ReportsFeeCollectionRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/lo-wise-group-realizable': {
      id: '/reports/lo-wise-group-realizable'
      path: '/lo-wise-group-realizable'
      fullPath: '/reports/lo-wise-group-realizable'
      preLoaderRoute: typeof ReportsLoWiseGroupRealizableRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/loan-closure': {
      id: '/reports/loan-closure'
      path: '/loan-closure'
      fullPath: '/reports/loan-closure'
      preLoaderRoute: typeof ReportsLoanClosureRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/master-roll': {
      id: '/reports/master-roll'
      path: '/master-roll'
      fullPath: '/reports/master-roll'
      preLoaderRoute: typeof ReportsMasterRollRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/outstanding': {
      id: '/reports/outstanding'
      path: '/outstanding'
      fullPath: '/reports/outstanding'
      preLoaderRoute: typeof ReportsOutstandingRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/overdue-collection-list': {
      id: '/reports/overdue-collection-list'
      path: '/overdue-collection-list'
      fullPath: '/reports/overdue-collection-list'
      preLoaderRoute: typeof ReportsOverdueCollectionListRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/par': {
      id: '/reports/par'
      path: '/par'
      fullPath: '/reports/par'
      preLoaderRoute: typeof ReportsParRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/reversals': {
      id: '/reports/reversals'
      path: '/reversals'
      fullPath: '/reports/reversals'
      preLoaderRoute: typeof ReportsReversalsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/savings': {
      id: '/reports/savings'
      path: '/savings'
      fullPath: '/reports/savings'
      preLoaderRoute: typeof ReportsSavingsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/transfers/group-interchange': {
      id: '/transfers/group-interchange'
      path: '/transfers/group-interchange'
      fullPath: '/transfers/group-interchange'
      preLoaderRoute: typeof TransfersGroupInterchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/group-officer': {
      id: '/transfers/group-officer'
      path: '/transfers/group-officer'
      fullPath: '/transfers/group-officer'
      preLoaderRoute: typeof TransfersGroupOfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/member': {
      id: '/transfers/member'
      path: '/transfers/member'
      fullPath: '/transfers/member'
      preLoaderRoute: typeof TransfersMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/receive': {
      id: '/transfers/receive'
      path: '/transfers/receive'
      fullPath: '/transfers/receive'
      preLoaderRoute: typeof TransfersReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteChildren {
  ReportsApprovalsRoute: typeof ReportsApprovalsRoute
  ReportsDailyOverdueRoute: typeof ReportsDailyOverdueRoute
  ReportsDayCollectionListRoute: typeof ReportsDayCollectionListRoute
  ReportsFeeCollectionRoute: typeof ReportsFeeCollectionRoute
  ReportsLoWiseGroupRealizableRoute: typeof ReportsLoWiseGroupRealizableRoute
  ReportsLoanClosureRoute: typeof ReportsLoanClosureRoute
  ReportsMasterRollRoute: typeof ReportsMasterRollRoute
  ReportsOutstandingRoute: typeof ReportsOutstandingRoute
  ReportsOverdueCollectionListRoute: typeof ReportsOverdueCollectionListRoute
  ReportsParRoute: typeof ReportsParRoute
  ReportsReversalsRoute: typeof ReportsReversalsRoute
  ReportsSavingsRoute: typeof ReportsSavingsRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsApprovalsRoute: ReportsApprovalsRoute,
  ReportsDailyOverdueRoute: ReportsDailyOverdueRoute,
  ReportsDayCollectionListRoute: ReportsDayCollectionListRoute,
  ReportsFeeCollectionRoute: ReportsFeeCollectionRoute,
  ReportsLoWiseGroupRealizableRoute: ReportsLoWiseGroupRealizableRoute,
  ReportsLoanClosureRoute: ReportsLoanClosureRoute,
  ReportsMasterRollRoute: ReportsMasterRollRoute,
  ReportsOutstandingRoute: ReportsOutstandingRoute,
  ReportsOverdueCollectionListRoute: ReportsOverdueCollectionListRoute,
  ReportsParRoute: ReportsParRoute,
  ReportsReversalsRoute: ReportsReversalsRoute,
  ReportsSavingsRoute: ReportsSavingsRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionSalesRoute: AdmissionSalesRoute,
  AdvanceCollectionRoute: AdvanceCollectionRoute,
  AuditRoute: AuditRoute,
  AuditLogsRoute: AuditLogsRoute,
  BadDebtsCollectionRoute: BadDebtsCollectionRoute,
  BadLoansRoute: BadLoansRoute,
  BankManagementRoute: BankManagementRoute,
  BranchesRoute: BranchesRoute,
  CalculatorRoute: CalculatorRoute,
  ClientGroupsRoute: ClientGroupsRoute,
  ClientsRoute: ClientsRoute,
  ExpensesRoute: ExpensesRoute,
  GroupCollectionRoute: GroupCollectionRoute,
  GroupCreateRoute: GroupCreateRoute,
  LoanApplicationsRoute: LoanApplicationsRoute,
  LoanProductsRoute: LoanProductsRoute,
  LoanRejectedRoute: LoanRejectedRoute,
  LoanRollbackRoute: LoanRollbackRoute,
  LoanSettlementRoute: LoanSettlementRoute,
  LoanWaitingApprovalRoute: LoanWaitingApprovalRoute,
  LoanWaitingDisburseRoute: LoanWaitingDisburseRoute,
  LoanWriteoffRoute: LoanWriteoffRoute,
  LoginRoute: LoginRoute,
  MemberAdmissionRoute: MemberAdmissionRoute,
  MemberDeathApplicationRoute: MemberDeathApplicationRoute,
  MemberDeathListRoute: MemberDeathListRoute,
  MemberInactiveRoute: MemberInactiveRoute,
  MemberListRoute: MemberListRoute,
  MemberRejectedRoute: MemberRejectedRoute,
  MemberWaitingApprovalRoute: MemberWaitingApprovalRoute,
  OverdueCollectionRoute: OverdueCollectionRoute,
  ProfileRoute: ProfileRoute,
  RepaymentsRoute: RepaymentsRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SavingsRoute: SavingsRoute,
  SavingsAccountsRoute: SavingsAccountsRoute,
  SecurityReturnsRoute: SecurityReturnsRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  GroupsRejectedRoute: GroupsRejectedRoute,
  GroupsWaitingApprovalRoute: GroupsWaitingApprovalRoute,
  TransfersGroupInterchangeRoute: TransfersGroupInterchangeRoute,
  TransfersGroupOfficerRoute: TransfersGroupOfficerRoute,
  TransfersMemberRoute: TransfersMemberRoute,
  TransfersReceiveRoute: TransfersReceiveRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
